CREATE TABLE IF NOT EXISTS magic_flow_knowledge (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    name VARCHAR(255) NOT NULL DEFAULT '',
    description VARCHAR(1000) NOT NULL DEFAULT '',
    type INT NOT NULL DEFAULT 1,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    business_id VARCHAR(255) NOT NULL DEFAULT '',
    sync_status INT NOT NULL DEFAULT 0,
    sync_status_message VARCHAR(1000) NOT NULL DEFAULT '',
    model VARCHAR(255) NOT NULL DEFAULT '',
    vector_db VARCHAR(255) NOT NULL DEFAULT '',
    organization_code VARCHAR(255) NOT NULL DEFAULT '',
    created_uid VARCHAR(255) NOT NULL DEFAULT '',
    updated_uid VARCHAR(255) NOT NULL DEFAULT '',
    expected_num INT NOT NULL DEFAULT 0,
    completed_num INT NOT NULL DEFAULT 0,
    retrieve_config JSON NULL,
    fragment_config JSON NULL,
    embedding_config JSON NULL,
    word_count BIGINT NOT NULL DEFAULT 0,
    icon VARCHAR(255) NOT NULL DEFAULT '',
    source_type INT NULL,
    knowledge_base_type VARCHAR(64) NOT NULL DEFAULT 'flow_vector',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uk_magic_flow_knowledge_code (code),
    KEY idx_combined (organization_code, type, updated_at),
    KEY idx_magic_flow_knowledge_org_business_id (organization_code, business_id, id)
);

CREATE TABLE IF NOT EXISTS knowledge_base_documents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_code VARCHAR(255) NOT NULL,
    knowledge_base_code VARCHAR(255) NOT NULL,
    source_binding_id BIGINT NOT NULL DEFAULT 0,
    source_item_id BIGINT NOT NULL DEFAULT 0,
    auto_added BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
    code VARCHAR(255) NOT NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    doc_type INT UNSIGNED NOT NULL,
    doc_metadata JSON NULL,
    document_file JSON NULL,
    sync_status INT NOT NULL DEFAULT 0,
    sync_times INT NOT NULL DEFAULT 0,
    sync_status_message VARCHAR(1000) NOT NULL DEFAULT '',
    embedding_model VARCHAR(255) NOT NULL DEFAULT '',
    vector_db VARCHAR(255) NOT NULL DEFAULT '',
    retrieve_config JSON NULL,
    fragment_config JSON NULL,
    embedding_config JSON NULL,
    vector_db_config JSON NULL,
    word_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_uid VARCHAR(255) NOT NULL DEFAULT '',
    updated_uid VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    third_platform_type VARCHAR(255) NULL,
    third_file_id VARCHAR(255) NULL,
    UNIQUE KEY unique_knowledge_base_code_code_version (knowledge_base_code, code, version),
    KEY idx_kb_documents_code_id (code, id),
    KEY idx_kb_documents_org_kb (organization_code, knowledge_base_code),
    KEY idx_kb_documents_kb_third_file (third_platform_type(64), third_file_id(191), knowledge_base_code(191)),
    KEY idx_kb_documents_org_third_file (third_platform_type(64), third_file_id(191), organization_code(191)),
    KEY idx_kb_documents_source_binding_id_id (source_binding_id, id),
    KEY idx_kb_documents_source_item_id_id (source_item_id, id)
);

CREATE TABLE IF NOT EXISTS knowledge_source_bindings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_code VARCHAR(255) NOT NULL DEFAULT '',
    knowledge_base_code VARCHAR(255) NOT NULL DEFAULT '',
    provider VARCHAR(64) NOT NULL DEFAULT '',
    root_type VARCHAR(64) NOT NULL DEFAULT '',
    root_ref VARCHAR(255) NOT NULL DEFAULT '',
    sync_mode VARCHAR(32) NOT NULL DEFAULT 'manual',
    sync_config JSON NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_uid VARCHAR(255) NOT NULL DEFAULT '',
    updated_uid VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_kb_source_bindings_root (knowledge_base_code, provider, root_type, root_ref),
    KEY idx_kb_source_bindings_org_root_sync (organization_code, provider, root_type, root_ref, sync_mode),
    KEY idx_kb_source_bindings_provider_root (provider, root_ref, id)
);

CREATE TABLE IF NOT EXISTS knowledge_source_binding_targets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    binding_id BIGINT NOT NULL DEFAULT 0,
    target_type VARCHAR(32) NOT NULL DEFAULT '',
    target_ref VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_kb_source_binding_targets (binding_id, target_type, target_ref)
);

CREATE TABLE IF NOT EXISTS knowledge_source_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_code VARCHAR(255) NOT NULL DEFAULT '',
    provider VARCHAR(64) NOT NULL DEFAULT '',
    root_type VARCHAR(64) NOT NULL DEFAULT '',
    root_ref VARCHAR(255) NOT NULL DEFAULT '',
    group_ref VARCHAR(255) NOT NULL DEFAULT '',
    item_type VARCHAR(32) NOT NULL DEFAULT 'file',
    item_ref VARCHAR(255) NOT NULL DEFAULT '',
    display_name VARCHAR(255) NOT NULL DEFAULT '',
    extension VARCHAR(64) NOT NULL DEFAULT '',
    content_hash VARCHAR(255) NOT NULL DEFAULT '',
    snapshot_meta JSON NULL,
    last_resolved_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_source_items_provider_item (organization_code, provider, item_ref),
    KEY idx_source_items_item_ref (item_ref, id)
);

CREATE TABLE IF NOT EXISTS knowledge_source_binding_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    binding_id BIGINT NOT NULL DEFAULT 0,
    source_item_id BIGINT NOT NULL DEFAULT 0,
    resolve_reason VARCHAR(255) NOT NULL DEFAULT '',
    last_resolved_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_source_binding_items (binding_id, source_item_id)
);

CREATE TABLE IF NOT EXISTS knowledge_base_ingestion_sources (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_code VARCHAR(64) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    source_code VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    credential_ref VARCHAR(255) NOT NULL DEFAULT '',
    config JSON NOT NULL,
    sync_cursor JSON NULL,
    last_sync_status VARCHAR(32) NOT NULL DEFAULT '',
    last_sync_error VARCHAR(1024) NOT NULL DEFAULT '',
    last_synced_at DATETIME NULL,
    created_uid VARCHAR(64) NOT NULL DEFAULT '',
    updated_uid VARCHAR(64) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_kb_ingestion_source (organization_code, provider, source_code),
    KEY idx_kb_ingestion_source_enabled (organization_code, provider, enabled, id)
);

CREATE TABLE IF NOT EXISTS knowledge_base_ingestion_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_code VARCHAR(64) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    source_code VARCHAR(128) NOT NULL,
    item_ref VARCHAR(191) NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    title VARCHAR(512) NOT NULL DEFAULT '',
    source_url VARCHAR(1024) NOT NULL DEFAULT '',
    extension VARCHAR(32) NOT NULL DEFAULT 'md',
    raw_hash CHAR(64) NOT NULL DEFAULT '',
    clean_hash CHAR(64) NOT NULL DEFAULT '',
    clean_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cleaner_version VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    snapshot_meta JSON NULL,
    last_error VARCHAR(2048) NOT NULL DEFAULT '',
    last_pulled_at DATETIME NULL,
    last_cleaned_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_kb_ingestion_item (organization_code, provider, source_code, item_ref),
    KEY idx_kb_ingestion_item_status (organization_code, provider, source_code, status, id),
    KEY idx_kb_ingestion_item_clean_hash (organization_code, provider, source_code, clean_hash, id)
);

CREATE TABLE IF NOT EXISTS knowledge_base_ingestion_item_contents (
    item_id BIGINT NOT NULL PRIMARY KEY,
    organization_code VARCHAR(64) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    source_code VARCHAR(128) NOT NULL,
    item_ref VARCHAR(191) NOT NULL,
    clean_hash CHAR(64) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    content_format VARCHAR(32) NOT NULL DEFAULT 'markdown',
    content_charset VARCHAR(32) NOT NULL DEFAULT 'utf-8',
    content_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_kb_ingestion_content_lookup (organization_code, provider, source_code, item_ref),
    KEY idx_kb_ingestion_content_hash (organization_code, provider, source_code, clean_hash)
);

CREATE TABLE IF NOT EXISTS knowledge_base_ingestion_runs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    organization_code VARCHAR(64) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    source_code VARCHAR(128) NOT NULL,
    run_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    pulled_count INT UNSIGNED NOT NULL DEFAULT 0,
    changed_count INT UNSIGNED NOT NULL DEFAULT 0,
    cleaned_count INT UNSIGNED NOT NULL DEFAULT 0,
    skipped_count INT UNSIGNED NOT NULL DEFAULT 0,
    failed_count INT UNSIGNED NOT NULL DEFAULT 0,
    error_summary VARCHAR(2048) NOT NULL DEFAULT '',
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at DATETIME NULL,
    KEY idx_kb_ingestion_run_source (organization_code, provider, source_code, started_at)
);

CREATE TABLE IF NOT EXISTS knowledge_base_bindings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    knowledge_base_code VARCHAR(255) NOT NULL DEFAULT '',
    bind_type VARCHAR(64) NOT NULL DEFAULT '',
    bind_id VARCHAR(255) NOT NULL DEFAULT '',
    organization_code VARCHAR(255) NOT NULL DEFAULT '',
    created_uid VARCHAR(255) NOT NULL DEFAULT '',
    updated_uid VARCHAR(255) NOT NULL DEFAULT '',
    metadata JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_kb_bindings (knowledge_base_code, bind_type, bind_id),
    KEY idx_kb_bindings_org_bind (organization_code, bind_type, bind_id),
    KEY idx_kb_bindings_org_kb (organization_code, knowledge_base_code)
);

CREATE TABLE IF NOT EXISTS magic_flow_knowledge_fragment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    knowledge_code VARCHAR(255) NOT NULL DEFAULT '',
    document_code VARCHAR(255) NOT NULL DEFAULT '',
    parent_fragment_id BIGINT UNSIGNED NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    content TEXT NOT NULL,
    metadata JSON NULL,
    business_id VARCHAR(255) NOT NULL DEFAULT '',
    sync_status INT NOT NULL DEFAULT 0,
    sync_times INT NOT NULL DEFAULT 0,
    sync_status_message VARCHAR(1000) NOT NULL DEFAULT '',
    point_id VARCHAR(255) NOT NULL DEFAULT '',
    vector TEXT NULL,
    word_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_uid VARCHAR(255) NOT NULL DEFAULT '',
    updated_uid VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    KEY magic_flow_knowledge_fragment_knowledge_code_updated_at_index (knowledge_code, updated_at),
    KEY idx_knowledge_document_deleted_id (knowledge_code, document_code, deleted_at, id),
    KEY idx_knowledge_code_business_id (knowledge_code, business_id),
    KEY idx_fragment_point_id_id (point_id, id)
);

CREATE TABLE IF NOT EXISTS magic_super_magic_agents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(255) NOT NULL DEFAULT '',
    organization_code VARCHAR(255) NOT NULL DEFAULT '',
    deleted_at DATETIME NULL,
    KEY idx_super_magic_agents_org_code_deleted (organization_code, code, deleted_at)
);
