"""向用户提问，发出问题后立即结束当前 Agent 轮次，等待用户答复后重启"""

import asyncio
import json
import time
import uuid
from dataclasses import dataclass
from typing import ClassVar, Dict, List, Optional, Union

from pydantic import BaseModel, Field

from app.core.context.agent_context import AgentContext
from app.core.entity.message.server_message import (
    AskUserQuestionContent,
    AskUserResultContent,
    DisplayType,
    ToolDetail,
)
from app.tools.core.base_tool import BaseTool
from app.tools.core.base_tool_params import BaseToolParams
from app.tools.core.tool_decorator import tool
from app.utils.async_file_utils import (
    async_exists,
    async_read_json,
    async_unlink,
    async_write_json,
)
from agentlang.context.tool_context import ToolContext
from agentlang.logger import get_logger
from agentlang.tools.tool_result import ToolResult

logger = get_logger(__name__)

INTERNAL_TIMEOUT = 600  # 秒，与 PHP 侧 Redis TTL=3600s 相配合s

class QuestionItem(BaseModel):
    """单个子问题的描述"""
    sub_id: str = Field(description="<!--zh: 子问题唯一标识，必须由调用方生成（如短 UUID），用于答案提交时的 key 对应-->\nUnique identifier for this sub-question; must be generated by the caller (e.g. a short UUID). Used as the key when submitting answers.")
    question: str = Field(description="向用户展示的问题内容")
    interaction_type: str = Field(
        description="交互类型：confirm=是/否确认，input=自由文本输入，select=单选，multi_select=多选"
    )
    options: Optional[List[str]] = Field(
        default=None,
        description="选项列表，interaction_type 为 select 或 multi_select 时必填",
    )
    placeholder: Optional[str] = Field(
        default=None,
        description="input 类型时输入框的占位提示文字",
    )
    min_select: Optional[int] = Field(
        default=1,
        description="multi_select 时用户至少需要选择的数量，默认 1",
    )
    max_select: Optional[int] = Field(
        default=None,
        description="multi_select 时用户最多可选的数量，不传则不限制",
    )
    default_value: Optional[Union[str, List[str]]] = Field(
        default=None,
        description="""<!--zh: 用户超时或跳过时该子问题的默认值；multi_select 类型传列表，其余类型传字符串-->
Default value used when the user times out or skips this question. Pass a list for multi_select, a string for other types.""",
    )


@dataclass
class PendingQuestion:
    """记录一个等待用户回答的问题批次的相关上下文"""
    params: "AskUserParams"
    agent_context: AgentContext
    tool_call_id: str           # LLM 对话历史中对应 tool_call 的 id
    timeout_task: asyncio.Task  # 后台超时定时器任务
    expires_at: int = 0         # Unix 时间戳，超时时刻
    agent_name: str = ""        # 用于服务重启后重建 ChatHistory
    agent_id: str = ""          # 用于服务重启后重建 ChatHistory


class AskUserParams(BaseToolParams):
    questions: List[QuestionItem] = Field(
        description=(
            "<!--zh: 子问题列表，至少一个元素。单个问题就是数组里只有一个元素。"
            "每个子问题独立设置 interaction_type、options 等。"
            "interaction_type 可选值：confirm=是/否确认，input=自由文本输入，select=单选，multi_select=多选。"
            "提供 default_value 可在用户超时或跳过时自动填入默认答案，避免任务卡死。-->"
            "List of sub-questions; at least one element (single question = array with one element). "
            "Each sub-question requires a unique sub_id (generate a short UUID, e.g. '3f2a'), interaction_type, and options where applicable. "
            "interaction_type values: confirm=yes/no, input=free text, select=single choice, multi_select=multiple choice. "
            "Provide default_value per sub-question so execution can continue automatically on timeout or skip."
        )
    )


@tool()
class AskUserTool(BaseTool[AskUserParams]):
    """<!--zh
    当遇到以下情况时，必须调用本工具询问用户意见，不可自行假设或跳过：
    - 缺少必须知道的信息：任务所需关键信息缺失且无法合理推断，继续执行会产生错误结果
    - 重大决策：涉及方向性选择、重要策略或对结果影响深远的决定，需用户明确表态
    - 高危操作：即将执行不可撤销的操作（删除、覆盖、清空、发送、支付等），必须事先确认
    其他情况请优先用自身判断完成任务，不要过度打扰用户。
    支持一次性提问多个子问题（questions 数组），用户统一回答后 Agent 才恢复执行。
    单个问题也使用 questions 数组，只放一个元素即可。
    -->
    Call this tool to ask the user when encountering the following situations — do not assume or skip:
    - Missing must-know information: critical information required for the task is absent and cannot be reasonably inferred; proceeding would produce incorrect results
    - Major decisions: directional choices, important strategies, or decisions with far-reaching impact that require explicit user input
    - High-risk operations: about to perform an irreversible action (delete, overwrite, clear, send, pay, etc.) that must be confirmed in advance
    In other situations, use your own judgment to complete the task without interrupting the user unnecessarily.
    Supports asking multiple sub-questions at once via the questions array; the Agent resumes only after the user answers all of them.
    For a single question, use a one-element array.
    """

    # ToolFactory 对工具类进行单例缓存，_pending_questions 为进程级全局状态
    _pending_questions: ClassVar[Dict[str, PendingQuestion]] = {}

    async def set_extra_arguments(self, tool_context: ToolContext) -> None:
        """Pre-generate question_id, expiry and sub_ids before BEFORE_TOOL_CALL fires.

        sub_id is populated here (not in execute()) so the BEFORE_TOOL_CALL detail card
        and the Pydantic AskUserParams in execute() share the exact same sub_id values.
        """
        for q in tool_context.arguments.get("questions", []):
            if not q.get("sub_id"):
                q["sub_id"] = str(uuid.uuid4())  # fallback: LLM should always provide sub_id
        tool_context.arguments["question_id"] = tool_context.tool_call_id
        tool_context.arguments["expires_at"] = int(time.time()) + INTERNAL_TIMEOUT
        tool_context.arguments["status"] = "pending"

    async def get_tool_detail(self, tool_context: ToolContext, result: ToolResult, arguments: dict = None) -> Optional[ToolDetail]:
        """Build the AFTER_TOOL_CALL detail card from result.extra_info set by the ask_user close-out flow."""
        if not result or not result.extra_info:
            return None
        status = result.extra_info.get("status")
        answers = result.extra_info.get("answers", {})
        questions = result.extra_info.get("questions", [])
        if not status:
            return None
        return ToolDetail(
            type=DisplayType.ASK_USER,
            data=AskUserResultContent(
                status=status,
                questions=questions,
                answers=answers,
            ),
        )

    async def get_before_tool_detail(self, tool_context: ToolContext, arguments: dict = None) -> ToolDetail:
        """Build the BEFORE_TOOL_CALL detail card for ask_user.

        question_id / expires_at / status are system-injected by set_extra_arguments();
        questions is the LLM-supplied input.
        """
        return ToolDetail(
            type=DisplayType.ASK_USER,
            data=AskUserQuestionContent(
                question_id=tool_context.tool_call_id,
                questions=(arguments or {}).get("questions", []),
                expires_at=tool_context.arguments.get("expires_at", 0),
                status="pending",
            ),
        )

    async def execute(self, tool_context: ToolContext, params: AskUserParams) -> ToolResult:
        agent_context: AgentContext = tool_context.get_extension_typed("agent_context", AgentContext)

        # Read the question_id that was written into tool_context.arguments by
        # set_extra_arguments() before BEFORE_TOOL_CALL fired. Fall back to a new UUID
        # only if the BEFORE_TOOL_CALL path was bypassed (e.g. direct invocation in tests).
        question_id: str = tool_context.arguments.get("question_id") or str(uuid.uuid4())
        expires_at: int = tool_context.arguments.get("expires_at") or (int(time.time()) + INTERNAL_TIMEOUT)

        # tool_call_id 由框架（tool_executor）在调用前注入到 tool_context
        tool_call_id: str = tool_context.tool_call_id

        # The pending card was already pushed to the frontend via the BEFORE_TOOL_CALL
        # event handled by task_message_factory, so no extra stream write is needed here.

        # 2. 启动后台超时定时器（睡眠至 expires_at，若未被取消则触发超时）
        timeout_task = asyncio.create_task(
            self._timeout_watcher(question_id, expires_at, agent_context)
        )

        # 3. 获取 agent_name / agent_id（用于持久化，服务重启后可重建 ChatHistory）
        chat_history = getattr(agent_context, "chat_history", None)
        agent_name = chat_history.agent_name if chat_history else getattr(agent_context, "agent_name", "magic")
        agent_id = chat_history.agent_id if chat_history else "main"

        # 4. 注册待处理问题（供超时定时器和 MessageProcessor 使用）
        AskUserTool._pending_questions[question_id] = PendingQuestion(
            params=params,
            agent_context=agent_context,
            tool_call_id=tool_call_id,
            timeout_task=timeout_task,
            expires_at=expires_at,
            agent_name=agent_name,
            agent_id=agent_id,
        )

        # 5. 在 agent_context 上设置暂停标记（IdleMonitorService 检测到后不会提前销毁沙盒）
        agent_context.set_ask_user_pending(question_id)

        # 6. 持久化待处理问题（服务重启后恢复定时器使用）
        await AskUserTool._save_pending_to_file(
            question_id=question_id,
            tool_call_id=tool_call_id,
            expires_at=expires_at,
            params=params,
            agent_name=agent_name,
            agent_id=agent_id,
        )

        # 7. 返回 ASK_USER 信号：agent.py 检测到后不写入 ToolResult，直接退出主循环；
        #    真实答复将由 AskUserService.resume_after_ask_user 追加到历史。
        n = len(params.questions)
        return ToolResult(
            content=f"[ASK_USER:{question_id}] {n} 个问题已发送给用户，等待回答。",
            system="ASK_USER",
        )

    # ─── 后台超时定时器 ──────────────────────────────────────────────────────

    async def _timeout_watcher(
        self,
        question_id: str,
        expires_at: int,
        agent_context: AgentContext,
    ) -> None:
        """睡眠至 expires_at；若未被取消则触发超时流程"""
        try:
            # 每 60 秒刷新一次活动时间，防止 IdleMonitorService 提前终止沙盒
            while True:
                now = int(time.time())
                remaining = expires_at - now
                if remaining <= 0:
                    break
                await asyncio.sleep(min(60, remaining))
                agent_context.update_activity_time()
        except asyncio.CancelledError:
            # 用户已在超时前回答，定时器被取消，正常退出
            return

        # 超时：从 pending 中移除（如果已被 handle_ask_user_response 抢先处理则直接返回）
        pending = AskUserTool._pending_questions.pop(question_id, None)
        if not pending:
            return

        logger.info(f"ask_user 超时: question_id={question_id}")

        # 构建超时答案：每个子问题使用其 default_value（若有）
        timeout_answers = {
            q.sub_id: (q.default_value or "")
            for q in pending.params.questions
        }
        timeout_answer = json.dumps(timeout_answers, ensure_ascii=False)

        # 以超时结果通过 AskUserService 恢复 Agent
        from app.api.routes.messages import message_processor

        asyncio.create_task(
            message_processor.ask_user_service.resume_after_ask_user(
                message_processor,
                pending=pending,
                response_status="timeout",
                answer=timeout_answer,
            )
        )

    # ─── 持久化：保存 / 删除 / 恢复 ─────────────────────────────────────────

    @classmethod
    async def _save_pending_to_file(
        cls,
        question_id: str,
        tool_call_id: str,
        expires_at: int,
        params: AskUserParams,
        agent_name: str,
        agent_id: str,
    ) -> None:
        """将待处理问题持久化到 .chat_history/ask_user_pending.json"""
        from app.path_manager import PathManager

        data = {
            "question_id": question_id,
            "tool_call_id": tool_call_id,
            "expires_at": expires_at,
            "agent_name": agent_name,
            "agent_id": agent_id,
            "params": {
                "questions": [q.model_dump() for q in params.questions],
            },
        }
        try:
            pending_file = PathManager.get_ask_user_pending_file()
            await async_write_json(pending_file, data)
            logger.info(f"已持久化 ask_user 待处理问题: question_id={question_id}, count={len(params.questions)}")
        except Exception as e:
            logger.error(f"持久化 ask_user 待处理问题失败: {e}", exc_info=True)

    @classmethod
    async def _delete_pending_file(cls) -> None:
        """删除持久化文件（问题已处理完毕）"""
        from app.path_manager import PathManager

        try:
            pending_file = PathManager.get_ask_user_pending_file()
            if await async_exists(pending_file):
                await async_unlink(pending_file)
                logger.info("已删除 ask_user 待处理问题持久化文件")
        except Exception as e:
            logger.error(f"删除 ask_user 持久化文件失败: {e}", exc_info=True)

    @classmethod
    async def restore_pending_timers(cls, agent_context: AgentContext) -> None:
        """服务重启后，从持久化文件恢复超时定时器。

        应在沙箱初始化完成后（initialize_workspace 结束时）调用。
        """
        from app.path_manager import PathManager
        from app.tools.core.tool_factory import tool_factory

        pending_file = PathManager.get_ask_user_pending_file()
        if not await async_exists(pending_file):
            return

        try:
            data = await async_read_json(pending_file)
        except Exception as e:
            logger.error(f"读取 ask_user 持久化文件失败: {e}", exc_info=True)
            return

        try:
            question_id = data["question_id"]
            tool_call_id = data["tool_call_id"]
            expires_at = data["expires_at"]
            agent_name = data.get("agent_name", "magic")
            agent_id = data.get("agent_id", "main")
            params = AskUserParams(**data["params"])
        except Exception as e:
            logger.error(f"解析 ask_user 持久化数据失败: {e}", exc_info=True)
            return

        # 若已在内存中（进程未重启，只是重复调用），跳过
        if question_id in cls._pending_questions:
            logger.info(f"ask_user 问题已在内存中，跳过恢复: question_id={question_id}")
            return

        # 通过 tool_factory 获取单例工具实例，用于启动定时器
        try:
            ask_user_instance = tool_factory.get_tool_instance("ask_user")
        except Exception:
            ask_user_instance = cls()

        timeout_task = asyncio.create_task(
            ask_user_instance._timeout_watcher(question_id, expires_at, agent_context)
        )

        pending = PendingQuestion(
            params=params,
            agent_context=agent_context,
            tool_call_id=tool_call_id,
            timeout_task=timeout_task,
            expires_at=expires_at,
            agent_name=agent_name,
            agent_id=agent_id,
        )
        cls._pending_questions[question_id] = pending

        # 重新标记暂停状态
        agent_context.set_ask_user_pending(question_id)

        remaining = expires_at - int(time.time())
        logger.info(
            f"已恢复 ask_user 超时定时器: question_id={question_id}, "
            f"count={len(params.questions)}, 剩余={max(0, remaining)}秒"
        )



# ─── 模块级辅助函数 ────────────────────────────────────────────────────────────

def _humanize_single(
    question: str,
    interaction_type: str,
    answer: Union[str, List[str]],
) -> str:
    """将单个子问题的答案转为自然语言描述（answered 状态专用）"""
    if interaction_type == "confirm":
        return f'"{question}"：{answer}'
    if interaction_type == "input":
        return f'"{question}"：{answer}'
    if interaction_type == "select":
        return f'"{question}"：选择了"{answer}"'
    if interaction_type == "multi_select":
        return f'"{question}"：选择了 {answer}'
    return f'"{question}"：{answer}'


def _humanize_batch(
    questions: List[QuestionItem],
    response_status: str,
    answers: dict,
) -> str:
    """将多个子问题的答复转为模型能直接理解的自然语言段落。

    answers 为 {sub_id: answer_str} 字典（对应前端提交的 JSON 对象）。
    使用模板而非额外 LLM 调用，保持低延迟、零额外成本。
    """
    if response_status == "timeout":
        parts = []
        for q in questions:
            dv = q.default_value
            if dv is not None:
                parts.append(f'"{q.question}"（超时，已用默认值：{dv}）')
            else:
                parts.append(f'"{q.question}"（超时，无默认值）')
        has_no_default = any(q.default_value is None for q in questions)
        summary = "；".join(parts)
        if has_no_default:
            return f"以下问题等待超时：{summary}。部分问题无默认值，请根据实际情况决定是否终止相关操作。"
        return f"以下问题等待超时，已按默认值继续：{summary}。请继续后续步骤。"

    if response_status == "skipped":
        parts = []
        for q in questions:
            dv = q.default_value
            if dv is not None:
                parts.append(f'"{q.question}"（已用默认值：{dv}）')
            else:
                parts.append(f'"{q.question}"（无默认值）')
        has_no_default = any(q.default_value is None for q in questions)
        summary = "；".join(parts)
        if has_no_default:
            return f"用户跳过了以下问题：{summary}。部分问题无默认值，请根据实际情况决定是否终止相关操作。"
        return f"用户跳过了以下问题，已按默认值继续：{summary}。请继续后续步骤。"

    # answered
    parts = []
    for q in questions:
        default: Union[str, List[str]] = [] if q.interaction_type == "multi_select" else ""
        ans = answers.get(q.sub_id, default)
        parts.append(_humanize_single(q.question, q.interaction_type, ans))
    summary = "；".join(parts)
    return f"用户已回答以下问题：{summary}。请据此继续执行。"
