// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_user.sql

package mysqlsqlc

import (
	"context"
	"strings"
)

const countActiveContactUserByUserID = `-- name: CountActiveContactUserByUserID :one
SELECT COUNT(*) AS count
FROM magic_contact_users
WHERE organization_code = ?
  AND user_id = ?
  AND status = 1
  AND deleted_at IS NULL
`

type CountActiveContactUserByUserIDParams struct {
	OrganizationCode string `json:"organization_code"`
	UserID           string `json:"user_id"`
}

func (q *Queries) CountActiveContactUserByUserID(ctx context.Context, arg CountActiveContactUserByUserIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveContactUserByUserID, arg.OrganizationCode, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActiveContactUserIDsByUserIDs = `-- name: ListActiveContactUserIDsByUserIDs :many
SELECT user_id
FROM magic_contact_users
WHERE organization_code = ?
  AND user_id IN (/*SLICE:user_ids*/?)
  AND status = 1
  AND deleted_at IS NULL
ORDER BY user_id ASC
`

type ListActiveContactUserIDsByUserIDsParams struct {
	OrganizationCode string   `json:"organization_code"`
	UserIds          []string `json:"user_ids"`
}

func (q *Queries) ListActiveContactUserIDsByUserIDs(ctx context.Context, arg ListActiveContactUserIDsByUserIDsParams) ([]string, error) {
	query := listActiveContactUserIDsByUserIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrganizationCode)
	if len(arg.UserIds) > 0 {
		for _, v := range arg.UserIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:user_ids*/?", strings.Repeat(",?", len(arg.UserIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:user_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveContactUsersByMagicID = `-- name: ListActiveContactUsersByMagicID :many
SELECT id, user_id, magic_id, organization_code
FROM magic_contact_users
WHERE organization_code = ?
  AND magic_id = ?
  AND status = 1
  AND deleted_at IS NULL
ORDER BY id ASC
`

type ListActiveContactUsersByMagicIDParams struct {
	OrganizationCode string `json:"organization_code"`
	MagicID          string `json:"magic_id"`
}

type ListActiveContactUsersByMagicIDRow struct {
	ID               uint64 `json:"id"`
	UserID           string `json:"user_id"`
	MagicID          string `json:"magic_id"`
	OrganizationCode string `json:"organization_code"`
}

func (q *Queries) ListActiveContactUsersByMagicID(ctx context.Context, arg ListActiveContactUsersByMagicIDParams) ([]ListActiveContactUsersByMagicIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveContactUsersByMagicID, arg.OrganizationCode, arg.MagicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveContactUsersByMagicIDRow{}
	for rows.Next() {
		var i ListActiveContactUsersByMagicIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MagicID,
			&i.OrganizationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveContactUsersByMagicIDs = `-- name: ListActiveContactUsersByMagicIDs :many
SELECT id, user_id, magic_id, organization_code
FROM magic_contact_users
WHERE organization_code = ?
  AND magic_id IN (/*SLICE:magic_ids*/?)
  AND status = 1
  AND deleted_at IS NULL
ORDER BY magic_id ASC, id ASC
`

type ListActiveContactUsersByMagicIDsParams struct {
	OrganizationCode string   `json:"organization_code"`
	MagicIds         []string `json:"magic_ids"`
}

type ListActiveContactUsersByMagicIDsRow struct {
	ID               uint64 `json:"id"`
	UserID           string `json:"user_id"`
	MagicID          string `json:"magic_id"`
	OrganizationCode string `json:"organization_code"`
}

func (q *Queries) ListActiveContactUsersByMagicIDs(ctx context.Context, arg ListActiveContactUsersByMagicIDsParams) ([]ListActiveContactUsersByMagicIDsRow, error) {
	query := listActiveContactUsersByMagicIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrganizationCode)
	if len(arg.MagicIds) > 0 {
		for _, v := range arg.MagicIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:magic_ids*/?", strings.Repeat(",?", len(arg.MagicIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:magic_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveContactUsersByMagicIDsRow{}
	for rows.Next() {
		var i ListActiveContactUsersByMagicIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MagicID,
			&i.OrganizationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
