// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
	"time"
)

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*)
FROM knowledge_base_documents d
WHERE d.deleted_at IS NULL
  AND (? IS NULL OR d.organization_code = ?)
  AND (? IS NULL OR d.knowledge_base_code = ?)
  AND (? IS NULL OR d.name LIKE ?)
  AND (? IS NULL OR d.doc_type = ?)
  AND (? IS NULL OR d.enabled = ?)
  AND (? IS NULL OR d.sync_status = ?)
`

type CountDocumentsParams struct {
	OrganizationCode  sql.NullString `json:"organization_code"`
	KnowledgeBaseCode sql.NullString `json:"knowledge_base_code"`
	NameLike          sql.NullString `json:"name_like"`
	DocType           sql.NullInt32  `json:"doc_type"`
	Enabled           sql.NullBool   `json:"enabled"`
	SyncStatus        sql.NullInt32  `json:"sync_status"`
}

func (q *Queries) CountDocuments(ctx context.Context, arg CountDocumentsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocuments,
		arg.OrganizationCode,
		arg.OrganizationCode,
		arg.KnowledgeBaseCode,
		arg.KnowledgeBaseCode,
		arg.NameLike,
		arg.NameLike,
		arg.DocType,
		arg.DocType,
		arg.Enabled,
		arg.Enabled,
		arg.SyncStatus,
		arg.SyncStatus,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByKnowledgeBaseCodes = `-- name: CountDocumentsByKnowledgeBaseCodes :many
SELECT knowledge_base_code, COUNT(*) AS count
FROM knowledge_base_documents
WHERE deleted_at IS NULL
  AND organization_code = ?
  AND knowledge_base_code IN (/*SLICE:knowledge_base_codes*/?)
GROUP BY knowledge_base_code
`

type CountDocumentsByKnowledgeBaseCodesParams struct {
	OrganizationCode   string   `json:"organization_code"`
	KnowledgeBaseCodes []string `json:"knowledge_base_codes"`
}

type CountDocumentsByKnowledgeBaseCodesRow struct {
	KnowledgeBaseCode string `json:"knowledge_base_code"`
	Count             int64  `json:"count"`
}

func (q *Queries) CountDocumentsByKnowledgeBaseCodes(ctx context.Context, arg CountDocumentsByKnowledgeBaseCodesParams) ([]CountDocumentsByKnowledgeBaseCodesRow, error) {
	query := countDocumentsByKnowledgeBaseCodes
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrganizationCode)
	if len(arg.KnowledgeBaseCodes) > 0 {
		for _, v := range arg.KnowledgeBaseCodes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:knowledge_base_codes*/?", strings.Repeat(",?", len(arg.KnowledgeBaseCodes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:knowledge_base_codes*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDocumentsByKnowledgeBaseCodesRow{}
	for rows.Next() {
		var i CountDocumentsByKnowledgeBaseCodesRow
		if err := rows.Scan(&i.KnowledgeBaseCode, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDocumentByID = `-- name: DeleteDocumentByID :execrows
DELETE FROM knowledge_base_documents
WHERE id = ?
`

func (q *Queries) DeleteDocumentByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocumentByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteDocumentsByKnowledgeBase = `-- name: DeleteDocumentsByKnowledgeBase :execrows
DELETE FROM knowledge_base_documents
WHERE knowledge_base_code = ?
`

func (q *Queries) DeleteDocumentsByKnowledgeBase(ctx context.Context, knowledgeBaseCode string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocumentsByKnowledgeBase, knowledgeBaseCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findDocumentByCode = `-- name: FindDocumentByCode :one
SELECT id, organization_code, knowledge_base_code, source_binding_id, source_item_id, auto_added, name, description, code,
       enabled, doc_type, doc_metadata, document_file, sync_status, sync_times, sync_status_message, embedding_model, vector_db,
       retrieve_config, fragment_config, embedding_config, vector_db_config, word_count, third_platform_type, third_file_id,
       created_uid, updated_uid, created_at, updated_at, deleted_at
FROM knowledge_base_documents
WHERE code = ?
  AND deleted_at IS NULL
ORDER BY id DESC
LIMIT 1
`

type FindDocumentByCodeRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
}

func (q *Queries) FindDocumentByCode(ctx context.Context, code string) (FindDocumentByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByCode, code)
	var i FindDocumentByCodeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findDocumentByCodeAndKnowledgeBase = `-- name: FindDocumentByCodeAndKnowledgeBase :one
SELECT id, organization_code, knowledge_base_code, source_binding_id, source_item_id, auto_added, name, description, code,
       enabled, doc_type, doc_metadata, document_file, sync_status, sync_times, sync_status_message, embedding_model, vector_db,
       retrieve_config, fragment_config, embedding_config, vector_db_config, word_count, third_platform_type, third_file_id,
       created_uid, updated_uid, created_at, updated_at, deleted_at
FROM knowledge_base_documents
WHERE code = ?
  AND knowledge_base_code = ?
  AND deleted_at IS NULL
ORDER BY id DESC
LIMIT 1
`

type FindDocumentByCodeAndKnowledgeBaseParams struct {
	Code              string `json:"code"`
	KnowledgeBaseCode string `json:"knowledge_base_code"`
}

type FindDocumentByCodeAndKnowledgeBaseRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
}

func (q *Queries) FindDocumentByCodeAndKnowledgeBase(ctx context.Context, arg FindDocumentByCodeAndKnowledgeBaseParams) (FindDocumentByCodeAndKnowledgeBaseRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByCodeAndKnowledgeBase, arg.Code, arg.KnowledgeBaseCode)
	var i FindDocumentByCodeAndKnowledgeBaseRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findDocumentByCodeAndKnowledgeBaseCompat = `-- name: FindDocumentByCodeAndKnowledgeBaseCompat :one
SELECT d.id, d.organization_code, d.knowledge_base_code, d.source_binding_id, d.source_item_id, d.auto_added, d.name, d.description, d.code,
       d.enabled, d.doc_type, COALESCE(d.doc_metadata, CAST('null' AS JSON)) AS doc_metadata, COALESCE(d.document_file, CAST('null' AS JSON)) AS document_file,
       d.sync_status, d.sync_times, d.sync_status_message, d.embedding_model, d.vector_db,
       COALESCE(d.retrieve_config, CAST('null' AS JSON)) AS retrieve_config, COALESCE(d.fragment_config, CAST('null' AS JSON)) AS fragment_config,
       COALESCE(d.embedding_config, CAST('null' AS JSON)) AS embedding_config, COALESCE(d.vector_db_config, CAST('null' AS JSON)) AS vector_db_config,
       d.word_count, d.third_platform_type, d.third_file_id, d.created_uid, d.updated_uid, d.created_at, d.updated_at, d.deleted_at,
       COALESCE(b.provider, '') AS source_provider, COALESCE(b.root_ref, '') AS binding_root_ref, COALESCE(si.item_ref, '') AS source_item_ref
FROM knowledge_base_documents d
LEFT JOIN knowledge_source_bindings b ON b.id = d.source_binding_id
LEFT JOIN knowledge_source_items si ON si.id = d.source_item_id
WHERE d.code = ?
  AND d.knowledge_base_code = ?
  AND d.deleted_at IS NULL
ORDER BY d.id DESC
LIMIT 1
`

type FindDocumentByCodeAndKnowledgeBaseCompatParams struct {
	Code              string `json:"code"`
	KnowledgeBaseCode string `json:"knowledge_base_code"`
}

type FindDocumentByCodeAndKnowledgeBaseCompatRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
	SourceProvider    string          `json:"source_provider"`
	BindingRootRef    string          `json:"binding_root_ref"`
	SourceItemRef     string          `json:"source_item_ref"`
}

func (q *Queries) FindDocumentByCodeAndKnowledgeBaseCompat(ctx context.Context, arg FindDocumentByCodeAndKnowledgeBaseCompatParams) (FindDocumentByCodeAndKnowledgeBaseCompatRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByCodeAndKnowledgeBaseCompat, arg.Code, arg.KnowledgeBaseCode)
	var i FindDocumentByCodeAndKnowledgeBaseCompatRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SourceProvider,
		&i.BindingRootRef,
		&i.SourceItemRef,
	)
	return i, err
}

const findDocumentByCodeCompat = `-- name: FindDocumentByCodeCompat :one
SELECT d.id, d.organization_code, d.knowledge_base_code, d.source_binding_id, d.source_item_id, d.auto_added, d.name, d.description, d.code,
       d.enabled, d.doc_type, COALESCE(d.doc_metadata, CAST('null' AS JSON)) AS doc_metadata, COALESCE(d.document_file, CAST('null' AS JSON)) AS document_file,
       d.sync_status, d.sync_times, d.sync_status_message, d.embedding_model, d.vector_db,
       COALESCE(d.retrieve_config, CAST('null' AS JSON)) AS retrieve_config, COALESCE(d.fragment_config, CAST('null' AS JSON)) AS fragment_config,
       COALESCE(d.embedding_config, CAST('null' AS JSON)) AS embedding_config, COALESCE(d.vector_db_config, CAST('null' AS JSON)) AS vector_db_config,
       d.word_count, d.third_platform_type, d.third_file_id, d.created_uid, d.updated_uid, d.created_at, d.updated_at, d.deleted_at,
       COALESCE(b.provider, '') AS source_provider, COALESCE(b.root_ref, '') AS binding_root_ref, COALESCE(si.item_ref, '') AS source_item_ref
FROM knowledge_base_documents d
LEFT JOIN knowledge_source_bindings b ON b.id = d.source_binding_id
LEFT JOIN knowledge_source_items si ON si.id = d.source_item_id
WHERE d.code = ?
  AND d.deleted_at IS NULL
ORDER BY d.id DESC
LIMIT 1
`

type FindDocumentByCodeCompatRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
	SourceProvider    string          `json:"source_provider"`
	BindingRootRef    string          `json:"binding_root_ref"`
	SourceItemRef     string          `json:"source_item_ref"`
}

func (q *Queries) FindDocumentByCodeCompat(ctx context.Context, code string) (FindDocumentByCodeCompatRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByCodeCompat, code)
	var i FindDocumentByCodeCompatRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SourceProvider,
		&i.BindingRootRef,
		&i.SourceItemRef,
	)
	return i, err
}

const findDocumentByID = `-- name: FindDocumentByID :one
SELECT id, organization_code, knowledge_base_code, source_binding_id, source_item_id, auto_added, name, description, code,
       enabled, doc_type, doc_metadata, document_file, sync_status, sync_times, sync_status_message, embedding_model, vector_db,
       retrieve_config, fragment_config, embedding_config, vector_db_config, word_count, third_platform_type, third_file_id,
       created_uid, updated_uid, created_at, updated_at, deleted_at
FROM knowledge_base_documents
WHERE id = ?
  AND deleted_at IS NULL
`

type FindDocumentByIDRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
}

func (q *Queries) FindDocumentByID(ctx context.Context, id int64) (FindDocumentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByID, id)
	var i FindDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findDocumentByIDCompat = `-- name: FindDocumentByIDCompat :one
SELECT d.id, d.organization_code, d.knowledge_base_code, d.source_binding_id, d.source_item_id, d.auto_added, d.name, d.description, d.code,
       d.enabled, d.doc_type, COALESCE(d.doc_metadata, CAST('null' AS JSON)) AS doc_metadata, COALESCE(d.document_file, CAST('null' AS JSON)) AS document_file,
       d.sync_status, d.sync_times, d.sync_status_message, d.embedding_model, d.vector_db,
       COALESCE(d.retrieve_config, CAST('null' AS JSON)) AS retrieve_config, COALESCE(d.fragment_config, CAST('null' AS JSON)) AS fragment_config,
       COALESCE(d.embedding_config, CAST('null' AS JSON)) AS embedding_config, COALESCE(d.vector_db_config, CAST('null' AS JSON)) AS vector_db_config,
       d.word_count, d.third_platform_type, d.third_file_id, d.created_uid, d.updated_uid, d.created_at, d.updated_at, d.deleted_at,
       COALESCE(b.provider, '') AS source_provider, COALESCE(b.root_ref, '') AS binding_root_ref, COALESCE(si.item_ref, '') AS source_item_ref
FROM knowledge_base_documents d
LEFT JOIN knowledge_source_bindings b ON b.id = d.source_binding_id
LEFT JOIN knowledge_source_items si ON si.id = d.source_item_id
WHERE d.id = ?
  AND d.deleted_at IS NULL
LIMIT 1
`

type FindDocumentByIDCompatRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
	SourceProvider    string          `json:"source_provider"`
	BindingRootRef    string          `json:"binding_root_ref"`
	SourceItemRef     string          `json:"source_item_ref"`
}

func (q *Queries) FindDocumentByIDCompat(ctx context.Context, id int64) (FindDocumentByIDCompatRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByIDCompat, id)
	var i FindDocumentByIDCompatRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SourceProvider,
		&i.BindingRootRef,
		&i.SourceItemRef,
	)
	return i, err
}

const findDocumentByKnowledgeBaseAndProjectFile = `-- name: FindDocumentByKnowledgeBaseAndProjectFile :one
SELECT d.id, d.organization_code, d.knowledge_base_code, d.source_binding_id, d.source_item_id, d.auto_added, d.name, d.description, d.code,
       d.enabled, d.doc_type, d.doc_metadata, d.document_file, d.sync_status, d.sync_times, d.sync_status_message, d.embedding_model, d.vector_db,
       d.retrieve_config, d.fragment_config, d.embedding_config, d.vector_db_config, d.word_count, d.third_platform_type, d.third_file_id,
       d.created_uid, d.updated_uid, d.created_at, d.updated_at, d.deleted_at
FROM knowledge_base_documents d
INNER JOIN knowledge_source_bindings b ON b.id = d.source_binding_id
INNER JOIN knowledge_source_items si ON si.id = d.source_item_id
WHERE d.knowledge_base_code = ?
  AND b.provider = 'project'
  AND si.item_ref = ?
  AND d.deleted_at IS NULL
ORDER BY d.id DESC
LIMIT 1
`

type FindDocumentByKnowledgeBaseAndProjectFileParams struct {
	KnowledgeBaseCode string `json:"knowledge_base_code"`
	ItemRef           string `json:"item_ref"`
}

type FindDocumentByKnowledgeBaseAndProjectFileRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
}

func (q *Queries) FindDocumentByKnowledgeBaseAndProjectFile(ctx context.Context, arg FindDocumentByKnowledgeBaseAndProjectFileParams) (FindDocumentByKnowledgeBaseAndProjectFileRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByKnowledgeBaseAndProjectFile, arg.KnowledgeBaseCode, arg.ItemRef)
	var i FindDocumentByKnowledgeBaseAndProjectFileRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findDocumentByKnowledgeBaseAndProjectFileCompat = `-- name: FindDocumentByKnowledgeBaseAndProjectFileCompat :one
SELECT d.id, d.organization_code, d.knowledge_base_code, d.source_binding_id, d.source_item_id, d.auto_added, d.name, d.description, d.code,
       d.enabled, d.doc_type, COALESCE(d.doc_metadata, CAST('null' AS JSON)) AS doc_metadata, COALESCE(d.document_file, CAST('null' AS JSON)) AS document_file,
       d.sync_status, d.sync_times, d.sync_status_message, d.embedding_model, d.vector_db,
       COALESCE(d.retrieve_config, CAST('null' AS JSON)) AS retrieve_config, COALESCE(d.fragment_config, CAST('null' AS JSON)) AS fragment_config,
       COALESCE(d.embedding_config, CAST('null' AS JSON)) AS embedding_config, COALESCE(d.vector_db_config, CAST('null' AS JSON)) AS vector_db_config,
       d.word_count, d.third_platform_type, d.third_file_id, d.created_uid, d.updated_uid, d.created_at, d.updated_at, d.deleted_at,
       COALESCE(b.provider, '') AS source_provider, COALESCE(b.root_ref, '') AS binding_root_ref, COALESCE(si.item_ref, '') AS source_item_ref
FROM knowledge_base_documents d
INNER JOIN knowledge_source_bindings b ON b.id = d.source_binding_id
INNER JOIN knowledge_source_items si ON si.id = d.source_item_id
WHERE d.knowledge_base_code = ?
  AND b.provider = 'project'
  AND si.item_ref = ?
  AND d.deleted_at IS NULL
ORDER BY d.id DESC
LIMIT 1
`

type FindDocumentByKnowledgeBaseAndProjectFileCompatParams struct {
	KnowledgeBaseCode string `json:"knowledge_base_code"`
	ItemRef           string `json:"item_ref"`
}

type FindDocumentByKnowledgeBaseAndProjectFileCompatRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
	SourceProvider    string          `json:"source_provider"`
	BindingRootRef    string          `json:"binding_root_ref"`
	SourceItemRef     string          `json:"source_item_ref"`
}

func (q *Queries) FindDocumentByKnowledgeBaseAndProjectFileCompat(ctx context.Context, arg FindDocumentByKnowledgeBaseAndProjectFileCompatParams) (FindDocumentByKnowledgeBaseAndProjectFileCompatRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByKnowledgeBaseAndProjectFileCompat, arg.KnowledgeBaseCode, arg.ItemRef)
	var i FindDocumentByKnowledgeBaseAndProjectFileCompatRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SourceProvider,
		&i.BindingRootRef,
		&i.SourceItemRef,
	)
	return i, err
}

const findDocumentByThirdFile = `-- name: FindDocumentByThirdFile :one
SELECT id, organization_code, knowledge_base_code, source_binding_id, source_item_id, auto_added, name, description, code,
       enabled, doc_type, doc_metadata, document_file, sync_status, sync_times, sync_status_message, embedding_model, vector_db,
       retrieve_config, fragment_config, embedding_config, vector_db_config, word_count, third_platform_type, third_file_id,
       created_uid, updated_uid, created_at, updated_at, deleted_at
FROM knowledge_base_documents
WHERE third_platform_type = ?
  AND third_file_id = ?
  AND deleted_at IS NULL
ORDER BY id DESC
LIMIT 1
`

type FindDocumentByThirdFileParams struct {
	ThirdPlatformType sql.NullString `json:"third_platform_type"`
	ThirdFileID       sql.NullString `json:"third_file_id"`
}

type FindDocumentByThirdFileRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
}

func (q *Queries) FindDocumentByThirdFile(ctx context.Context, arg FindDocumentByThirdFileParams) (FindDocumentByThirdFileRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByThirdFile, arg.ThirdPlatformType, arg.ThirdFileID)
	var i FindDocumentByThirdFileRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findDocumentByThirdFileCompat = `-- name: FindDocumentByThirdFileCompat :one
SELECT d.id, d.organization_code, d.knowledge_base_code, d.source_binding_id, d.source_item_id, d.auto_added, d.name, d.description, d.code,
       d.enabled, d.doc_type, COALESCE(d.doc_metadata, CAST('null' AS JSON)) AS doc_metadata, COALESCE(d.document_file, CAST('null' AS JSON)) AS document_file,
       d.sync_status, d.sync_times, d.sync_status_message, d.embedding_model, d.vector_db,
       COALESCE(d.retrieve_config, CAST('null' AS JSON)) AS retrieve_config, COALESCE(d.fragment_config, CAST('null' AS JSON)) AS fragment_config,
       COALESCE(d.embedding_config, CAST('null' AS JSON)) AS embedding_config, COALESCE(d.vector_db_config, CAST('null' AS JSON)) AS vector_db_config,
       d.word_count, d.third_platform_type, d.third_file_id, d.created_uid, d.updated_uid, d.created_at, d.updated_at, d.deleted_at,
       COALESCE(b.provider, '') AS source_provider, COALESCE(b.root_ref, '') AS binding_root_ref, COALESCE(si.item_ref, '') AS source_item_ref
FROM knowledge_base_documents d
LEFT JOIN knowledge_source_bindings b ON b.id = d.source_binding_id
LEFT JOIN knowledge_source_items si ON si.id = d.source_item_id
WHERE d.third_platform_type = ?
  AND d.third_file_id = ?
  AND d.deleted_at IS NULL
ORDER BY d.id DESC
LIMIT 1
`

type FindDocumentByThirdFileCompatParams struct {
	ThirdPlatformType sql.NullString `json:"third_platform_type"`
	ThirdFileID       sql.NullString `json:"third_file_id"`
}

type FindDocumentByThirdFileCompatRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
	SourceProvider    string          `json:"source_provider"`
	BindingRootRef    string          `json:"binding_root_ref"`
	SourceItemRef     string          `json:"source_item_ref"`
}

func (q *Queries) FindDocumentByThirdFileCompat(ctx context.Context, arg FindDocumentByThirdFileCompatParams) (FindDocumentByThirdFileCompatRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentByThirdFileCompat, arg.ThirdPlatformType, arg.ThirdFileID)
	var i FindDocumentByThirdFileCompatRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SourceProvider,
		&i.BindingRootRef,
		&i.SourceItemRef,
	)
	return i, err
}

const findDocumentIncludingDeletedCompat = `-- name: FindDocumentIncludingDeletedCompat :one
SELECT d.id, d.organization_code, d.knowledge_base_code, d.source_binding_id, d.source_item_id, d.auto_added, d.name, d.description, d.code,
       d.enabled, d.doc_type, COALESCE(d.doc_metadata, CAST('null' AS JSON)) AS doc_metadata, COALESCE(d.document_file, CAST('null' AS JSON)) AS document_file,
       d.sync_status, d.sync_times, d.sync_status_message, d.embedding_model, d.vector_db,
       COALESCE(d.retrieve_config, CAST('null' AS JSON)) AS retrieve_config, COALESCE(d.fragment_config, CAST('null' AS JSON)) AS fragment_config,
       COALESCE(d.embedding_config, CAST('null' AS JSON)) AS embedding_config, COALESCE(d.vector_db_config, CAST('null' AS JSON)) AS vector_db_config,
       d.word_count, d.third_platform_type, d.third_file_id, d.created_uid, d.updated_uid, d.created_at, d.updated_at, d.deleted_at,
       COALESCE(b.provider, '') AS source_provider, COALESCE(b.root_ref, '') AS binding_root_ref, COALESCE(si.item_ref, '') AS source_item_ref
FROM knowledge_base_documents d
LEFT JOIN knowledge_source_bindings b ON b.id = d.source_binding_id
LEFT JOIN knowledge_source_items si ON si.id = d.source_item_id
WHERE d.knowledge_base_code = ?
  AND d.code = ?
ORDER BY d.id DESC
LIMIT 1
`

type FindDocumentIncludingDeletedCompatParams struct {
	KnowledgeBaseCode string `json:"knowledge_base_code"`
	Code              string `json:"code"`
}

type FindDocumentIncludingDeletedCompatRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
	SourceProvider    string          `json:"source_provider"`
	BindingRootRef    string          `json:"binding_root_ref"`
	SourceItemRef     string          `json:"source_item_ref"`
}

func (q *Queries) FindDocumentIncludingDeletedCompat(ctx context.Context, arg FindDocumentIncludingDeletedCompatParams) (FindDocumentIncludingDeletedCompatRow, error) {
	row := q.db.QueryRowContext(ctx, findDocumentIncludingDeletedCompat, arg.KnowledgeBaseCode, arg.Code)
	var i FindDocumentIncludingDeletedCompatRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.KnowledgeBaseCode,
		&i.SourceBindingID,
		&i.SourceItemID,
		&i.AutoAdded,
		&i.Name,
		&i.Description,
		&i.Code,
		&i.Enabled,
		&i.DocType,
		&i.DocMetadata,
		&i.DocumentFile,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.EmbeddingModel,
		&i.VectorDb,
		&i.RetrieveConfig,
		&i.FragmentConfig,
		&i.EmbeddingConfig,
		&i.VectorDbConfig,
		&i.WordCount,
		&i.ThirdPlatformType,
		&i.ThirdFileID,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SourceProvider,
		&i.BindingRootRef,
		&i.SourceItemRef,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :execresult
INSERT INTO knowledge_base_documents (
  organization_code, knowledge_base_code, source_binding_id, source_item_id, auto_added, name, description, code,
  enabled, doc_type, doc_metadata, document_file,
  sync_status, sync_times, sync_status_message, embedding_model, vector_db,
  retrieve_config, fragment_config, embedding_config, vector_db_config, word_count,
  created_uid, updated_uid, created_at, updated_at, third_platform_type, third_file_id
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertDocumentParams struct {
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertDocument,
		arg.OrganizationCode,
		arg.KnowledgeBaseCode,
		arg.SourceBindingID,
		arg.SourceItemID,
		arg.AutoAdded,
		arg.Name,
		arg.Description,
		arg.Code,
		arg.Enabled,
		arg.DocType,
		arg.DocMetadata,
		arg.DocumentFile,
		arg.SyncStatus,
		arg.SyncTimes,
		arg.SyncStatusMessage,
		arg.EmbeddingModel,
		arg.VectorDb,
		arg.RetrieveConfig,
		arg.FragmentConfig,
		arg.EmbeddingConfig,
		arg.VectorDbConfig,
		arg.WordCount,
		arg.CreatedUid,
		arg.UpdatedUid,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ThirdPlatformType,
		arg.ThirdFileID,
	)
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, organization_code, knowledge_base_code, source_binding_id, source_item_id, auto_added, name, description, code,
       enabled, doc_type, doc_metadata, document_file, sync_status, sync_times, sync_status_message, embedding_model, vector_db,
       retrieve_config, fragment_config, embedding_config, vector_db_config, word_count, third_platform_type, third_file_id,
       created_uid, updated_uid, created_at, updated_at, deleted_at
FROM knowledge_base_documents
WHERE deleted_at IS NULL
  AND (? IS NULL OR organization_code = ?)
  AND (? IS NULL OR knowledge_base_code = ?)
  AND (? IS NULL OR name LIKE ?)
  AND (? IS NULL OR doc_type = ?)
  AND (? IS NULL OR enabled = ?)
  AND (? IS NULL OR sync_status = ?)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListDocumentsParams struct {
	OrganizationCode  sql.NullString `json:"organization_code"`
	KnowledgeBaseCode sql.NullString `json:"knowledge_base_code"`
	NameLike          sql.NullString `json:"name_like"`
	DocType           sql.NullInt32  `json:"doc_type"`
	Enabled           sql.NullBool   `json:"enabled"`
	SyncStatus        sql.NullInt32  `json:"sync_status"`
	Limit             int32          `json:"limit"`
	Offset            int32          `json:"offset"`
}

type ListDocumentsRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments,
		arg.OrganizationCode,
		arg.OrganizationCode,
		arg.KnowledgeBaseCode,
		arg.KnowledgeBaseCode,
		arg.NameLike,
		arg.NameLike,
		arg.DocType,
		arg.DocType,
		arg.Enabled,
		arg.Enabled,
		arg.SyncStatus,
		arg.SyncStatus,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsRow{}
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationCode,
			&i.KnowledgeBaseCode,
			&i.SourceBindingID,
			&i.SourceItemID,
			&i.AutoAdded,
			&i.Name,
			&i.Description,
			&i.Code,
			&i.Enabled,
			&i.DocType,
			&i.DocMetadata,
			&i.DocumentFile,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.EmbeddingModel,
			&i.VectorDb,
			&i.RetrieveConfig,
			&i.FragmentConfig,
			&i.EmbeddingConfig,
			&i.VectorDbConfig,
			&i.WordCount,
			&i.ThirdPlatformType,
			&i.ThirdFileID,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByKnowledgeBaseAndProject = `-- name: ListDocumentsByKnowledgeBaseAndProject :many
SELECT d.id, d.organization_code, d.knowledge_base_code, d.source_binding_id, d.source_item_id, d.auto_added, d.name, d.description, d.code,
       d.enabled, d.doc_type, d.doc_metadata, d.document_file, d.sync_status, d.sync_times, d.sync_status_message, d.embedding_model, d.vector_db,
       d.retrieve_config, d.fragment_config, d.embedding_config, d.vector_db_config, d.word_count, d.third_platform_type, d.third_file_id,
       d.created_uid, d.updated_uid, d.created_at, d.updated_at, d.deleted_at
FROM knowledge_base_documents d
INNER JOIN knowledge_source_bindings b ON b.id = d.source_binding_id
WHERE d.knowledge_base_code = ?
  AND b.provider = 'project'
  AND b.root_ref = ?
  AND d.deleted_at IS NULL
ORDER BY d.id DESC
`

type ListDocumentsByKnowledgeBaseAndProjectParams struct {
	KnowledgeBaseCode string `json:"knowledge_base_code"`
	RootRef           string `json:"root_ref"`
}

type ListDocumentsByKnowledgeBaseAndProjectRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
}

func (q *Queries) ListDocumentsByKnowledgeBaseAndProject(ctx context.Context, arg ListDocumentsByKnowledgeBaseAndProjectParams) ([]ListDocumentsByKnowledgeBaseAndProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByKnowledgeBaseAndProject, arg.KnowledgeBaseCode, arg.RootRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsByKnowledgeBaseAndProjectRow{}
	for rows.Next() {
		var i ListDocumentsByKnowledgeBaseAndProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationCode,
			&i.KnowledgeBaseCode,
			&i.SourceBindingID,
			&i.SourceItemID,
			&i.AutoAdded,
			&i.Name,
			&i.Description,
			&i.Code,
			&i.Enabled,
			&i.DocType,
			&i.DocMetadata,
			&i.DocumentFile,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.EmbeddingModel,
			&i.VectorDb,
			&i.RetrieveConfig,
			&i.FragmentConfig,
			&i.EmbeddingConfig,
			&i.VectorDbConfig,
			&i.WordCount,
			&i.ThirdPlatformType,
			&i.ThirdFileID,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByKnowledgeBaseAndProjectCompat = `-- name: ListDocumentsByKnowledgeBaseAndProjectCompat :many
SELECT d.id, d.organization_code, d.knowledge_base_code, d.source_binding_id, d.source_item_id, d.auto_added, d.name, d.description, d.code,
       d.enabled, d.doc_type, COALESCE(d.doc_metadata, CAST('null' AS JSON)) AS doc_metadata, COALESCE(d.document_file, CAST('null' AS JSON)) AS document_file,
       d.sync_status, d.sync_times, d.sync_status_message, d.embedding_model, d.vector_db,
       COALESCE(d.retrieve_config, CAST('null' AS JSON)) AS retrieve_config, COALESCE(d.fragment_config, CAST('null' AS JSON)) AS fragment_config,
       COALESCE(d.embedding_config, CAST('null' AS JSON)) AS embedding_config, COALESCE(d.vector_db_config, CAST('null' AS JSON)) AS vector_db_config,
       d.word_count, d.third_platform_type, d.third_file_id, d.created_uid, d.updated_uid, d.created_at, d.updated_at, d.deleted_at,
       COALESCE(b.provider, '') AS source_provider, COALESCE(b.root_ref, '') AS binding_root_ref, COALESCE(si.item_ref, '') AS source_item_ref
FROM knowledge_base_documents d
INNER JOIN knowledge_source_bindings b ON b.id = d.source_binding_id
LEFT JOIN knowledge_source_items si ON si.id = d.source_item_id
WHERE d.knowledge_base_code = ?
  AND b.provider = 'project'
  AND b.root_ref = ?
  AND d.deleted_at IS NULL
ORDER BY d.id DESC
`

type ListDocumentsByKnowledgeBaseAndProjectCompatParams struct {
	KnowledgeBaseCode string `json:"knowledge_base_code"`
	RootRef           string `json:"root_ref"`
}

type ListDocumentsByKnowledgeBaseAndProjectCompatRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
	SourceProvider    string          `json:"source_provider"`
	BindingRootRef    string          `json:"binding_root_ref"`
	SourceItemRef     string          `json:"source_item_ref"`
}

func (q *Queries) ListDocumentsByKnowledgeBaseAndProjectCompat(ctx context.Context, arg ListDocumentsByKnowledgeBaseAndProjectCompatParams) ([]ListDocumentsByKnowledgeBaseAndProjectCompatRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByKnowledgeBaseAndProjectCompat, arg.KnowledgeBaseCode, arg.RootRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsByKnowledgeBaseAndProjectCompatRow{}
	for rows.Next() {
		var i ListDocumentsByKnowledgeBaseAndProjectCompatRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationCode,
			&i.KnowledgeBaseCode,
			&i.SourceBindingID,
			&i.SourceItemID,
			&i.AutoAdded,
			&i.Name,
			&i.Description,
			&i.Code,
			&i.Enabled,
			&i.DocType,
			&i.DocMetadata,
			&i.DocumentFile,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.EmbeddingModel,
			&i.VectorDb,
			&i.RetrieveConfig,
			&i.FragmentConfig,
			&i.EmbeddingConfig,
			&i.VectorDbConfig,
			&i.WordCount,
			&i.ThirdPlatformType,
			&i.ThirdFileID,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SourceProvider,
			&i.BindingRootRef,
			&i.SourceItemRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByProjectFileInOrgCompat = `-- name: ListDocumentsByProjectFileInOrgCompat :many
SELECT d.id, d.organization_code, d.knowledge_base_code, d.source_binding_id, d.source_item_id, d.auto_added, d.name, d.description, d.code,
       d.enabled, d.doc_type, COALESCE(d.doc_metadata, CAST('null' AS JSON)) AS doc_metadata, COALESCE(d.document_file, CAST('null' AS JSON)) AS document_file,
       d.sync_status, d.sync_times, d.sync_status_message, d.embedding_model, d.vector_db,
       COALESCE(d.retrieve_config, CAST('null' AS JSON)) AS retrieve_config, COALESCE(d.fragment_config, CAST('null' AS JSON)) AS fragment_config,
       COALESCE(d.embedding_config, CAST('null' AS JSON)) AS embedding_config, COALESCE(d.vector_db_config, CAST('null' AS JSON)) AS vector_db_config,
       d.word_count, d.third_platform_type, d.third_file_id, d.created_uid, d.updated_uid, d.created_at, d.updated_at, d.deleted_at,
       COALESCE(b.provider, '') AS source_provider, COALESCE(b.root_ref, '') AS binding_root_ref, COALESCE(si.item_ref, '') AS source_item_ref
FROM knowledge_base_documents d
INNER JOIN knowledge_source_bindings b ON b.id = d.source_binding_id
INNER JOIN knowledge_source_items si ON si.id = d.source_item_id
WHERE d.organization_code = ?
  AND b.provider = 'project'
  AND si.item_ref = ?
  AND d.deleted_at IS NULL
ORDER BY d.id DESC
`

type ListDocumentsByProjectFileInOrgCompatParams struct {
	OrganizationCode string `json:"organization_code"`
	ItemRef          string `json:"item_ref"`
}

type ListDocumentsByProjectFileInOrgCompatRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
	SourceProvider    string          `json:"source_provider"`
	BindingRootRef    string          `json:"binding_root_ref"`
	SourceItemRef     string          `json:"source_item_ref"`
}

func (q *Queries) ListDocumentsByProjectFileInOrgCompat(ctx context.Context, arg ListDocumentsByProjectFileInOrgCompatParams) ([]ListDocumentsByProjectFileInOrgCompatRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByProjectFileInOrgCompat, arg.OrganizationCode, arg.ItemRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsByProjectFileInOrgCompatRow{}
	for rows.Next() {
		var i ListDocumentsByProjectFileInOrgCompatRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationCode,
			&i.KnowledgeBaseCode,
			&i.SourceBindingID,
			&i.SourceItemID,
			&i.AutoAdded,
			&i.Name,
			&i.Description,
			&i.Code,
			&i.Enabled,
			&i.DocType,
			&i.DocMetadata,
			&i.DocumentFile,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.EmbeddingModel,
			&i.VectorDb,
			&i.RetrieveConfig,
			&i.FragmentConfig,
			&i.EmbeddingConfig,
			&i.VectorDbConfig,
			&i.WordCount,
			&i.ThirdPlatformType,
			&i.ThirdFileID,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SourceProvider,
			&i.BindingRootRef,
			&i.SourceItemRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsBySourceFileID = `-- name: ListDocumentsBySourceFileID :many
SELECT id, organization_code, knowledge_base_code, source_binding_id, source_item_id, auto_added, name, description, code,
       enabled, doc_type, doc_metadata, document_file, sync_status, sync_times, sync_status_message, embedding_model, vector_db,
       retrieve_config, fragment_config, embedding_config, vector_db_config, word_count, third_platform_type, third_file_id,
       created_uid, updated_uid, created_at, updated_at, deleted_at
FROM knowledge_base_documents
WHERE source_item_id = ?
  AND deleted_at IS NULL
ORDER BY id DESC
`

type ListDocumentsBySourceFileIDRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Code              string          `json:"code"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         sql.NullTime    `json:"deleted_at"`
}

func (q *Queries) ListDocumentsBySourceFileID(ctx context.Context, sourceItemID int64) ([]ListDocumentsBySourceFileIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsBySourceFileID, sourceItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsBySourceFileIDRow{}
	for rows.Next() {
		var i ListDocumentsBySourceFileIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationCode,
			&i.KnowledgeBaseCode,
			&i.SourceBindingID,
			&i.SourceItemID,
			&i.AutoAdded,
			&i.Name,
			&i.Description,
			&i.Code,
			&i.Enabled,
			&i.DocType,
			&i.DocMetadata,
			&i.DocumentFile,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.EmbeddingModel,
			&i.VectorDb,
			&i.RetrieveConfig,
			&i.FragmentConfig,
			&i.EmbeddingConfig,
			&i.VectorDbConfig,
			&i.WordCount,
			&i.ThirdPlatformType,
			&i.ThirdFileID,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :execrows
UPDATE knowledge_base_documents
SET source_binding_id = ?,
    source_item_id = ?,
    auto_added = ?,
    name = ?,
    description = ?,
    enabled = ?,
    doc_type = ?,
    doc_metadata = ?,
    document_file = ?,
    sync_status = ?,
    sync_times = ?,
    sync_status_message = ?,
    embedding_model = ?,
    vector_db = ?,
    retrieve_config = ?,
    fragment_config = ?,
    embedding_config = ?,
    vector_db_config = ?,
    word_count = ?,
    third_platform_type = ?,
    third_file_id = ?,
    updated_uid = ?,
    updated_at = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type UpdateDocumentParams struct {
	SourceBindingID   int64           `json:"source_binding_id"`
	SourceItemID      int64           `json:"source_item_id"`
	AutoAdded         bool            `json:"auto_added"`
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	Enabled           bool            `json:"enabled"`
	DocType           uint32          `json:"doc_type"`
	DocMetadata       json.RawMessage `json:"doc_metadata"`
	DocumentFile      json.RawMessage `json:"document_file"`
	SyncStatus        int32           `json:"sync_status"`
	SyncTimes         int32           `json:"sync_times"`
	SyncStatusMessage string          `json:"sync_status_message"`
	EmbeddingModel    string          `json:"embedding_model"`
	VectorDb          string          `json:"vector_db"`
	RetrieveConfig    json.RawMessage `json:"retrieve_config"`
	FragmentConfig    json.RawMessage `json:"fragment_config"`
	EmbeddingConfig   json.RawMessage `json:"embedding_config"`
	VectorDbConfig    json.RawMessage `json:"vector_db_config"`
	WordCount         uint64          `json:"word_count"`
	ThirdPlatformType sql.NullString  `json:"third_platform_type"`
	ThirdFileID       sql.NullString  `json:"third_file_id"`
	UpdatedUid        string          `json:"updated_uid"`
	UpdatedAt         time.Time       `json:"updated_at"`
	ID                int64           `json:"id"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDocument,
		arg.SourceBindingID,
		arg.SourceItemID,
		arg.AutoAdded,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.DocType,
		arg.DocMetadata,
		arg.DocumentFile,
		arg.SyncStatus,
		arg.SyncTimes,
		arg.SyncStatusMessage,
		arg.EmbeddingModel,
		arg.VectorDb,
		arg.RetrieveConfig,
		arg.FragmentConfig,
		arg.EmbeddingConfig,
		arg.VectorDbConfig,
		arg.WordCount,
		arg.ThirdPlatformType,
		arg.ThirdFileID,
		arg.UpdatedUid,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDocumentSyncStatus = `-- name: UpdateDocumentSyncStatus :execrows
UPDATE knowledge_base_documents
SET sync_status = ?,
    sync_status_message = ?,
    updated_at = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type UpdateDocumentSyncStatusParams struct {
	SyncStatus        int32     `json:"sync_status"`
	SyncStatusMessage string    `json:"sync_status_message"`
	UpdatedAt         time.Time `json:"updated_at"`
	ID                int64     `json:"id"`
}

func (q *Queries) UpdateDocumentSyncStatus(ctx context.Context, arg UpdateDocumentSyncStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDocumentSyncStatus,
		arg.SyncStatus,
		arg.SyncStatusMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
