// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embedding_cache.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
	"time"
)

const basicStats = `-- name: BasicStats :one
SELECT COUNT(*) AS total_caches,
       CAST(COALESCE(SUM(access_count), 0) AS SIGNED) AS total_access_count,
       CAST(COALESCE(AVG(access_count), 0) AS DOUBLE) AS average_access_count,
       COUNT(DISTINCT embedding_model) AS unique_models,
       COALESCE(CAST(MIN(created_at) AS DATETIME), CAST('1970-01-01 00:00:00' AS DATETIME)) AS oldest_cache,
       COALESCE(CAST(MAX(created_at) AS DATETIME), CAST('1970-01-01 00:00:00' AS DATETIME)) AS newest_cache,
       COALESCE(CAST(MAX(last_accessed_at) AS DATETIME), CAST('1970-01-01 00:00:00' AS DATETIME)) AS last_access_time
FROM embedding_cache
`

type BasicStatsRow struct {
	TotalCaches        int64       `json:"total_caches"`
	TotalAccessCount   int64       `json:"total_access_count"`
	AverageAccessCount float64     `json:"average_access_count"`
	UniqueModels       int64       `json:"unique_models"`
	OldestCache        interface{} `json:"oldest_cache"`
	NewestCache        interface{} `json:"newest_cache"`
	LastAccessTime     interface{} `json:"last_access_time"`
}

func (q *Queries) BasicStats(ctx context.Context) (BasicStatsRow, error) {
	row := q.db.QueryRowContext(ctx, basicStats)
	var i BasicStatsRow
	err := row.Scan(
		&i.TotalCaches,
		&i.TotalAccessCount,
		&i.AverageAccessCount,
		&i.UniqueModels,
		&i.OldestCache,
		&i.NewestCache,
		&i.LastAccessTime,
	)
	return i, err
}

const countByModel = `-- name: CountByModel :one
SELECT COUNT(*) FROM embedding_cache WHERE embedding_model = ?
`

func (q *Queries) CountByModel(ctx context.Context, embeddingModel string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByModel, embeddingModel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCacheByHash = `-- name: DeleteCacheByHash :execrows
DELETE FROM embedding_cache WHERE text_hash = ?
`

func (q *Queries) DeleteCacheByHash(ctx context.Context, textHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCacheByHash, textHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCacheByID = `-- name: DeleteCacheByID :execrows
DELETE FROM embedding_cache WHERE id = ?
`

func (q *Queries) DeleteCacheByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCacheByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCachesByIDs = `-- name: DeleteCachesByIDs :execrows
DELETE FROM embedding_cache WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteCachesByIDs(ctx context.Context, ids []int64) (int64, error) {
	query := deleteCachesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const estimateStorage = `-- name: EstimateStorage :one
SELECT CAST(COALESCE(SUM(LENGTH(embedding) + LENGTH(text_preview)), 0) AS SIGNED) AS storage_size
FROM embedding_cache
`

func (q *Queries) EstimateStorage(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, estimateStorage)
	var storage_size int64
	err := row.Scan(&storage_size)
	return storage_size, err
}

const findCacheByHash = `-- name: FindCacheByHash :one
SELECT id, text_hash, text_preview, text_length, embedding, embedding_model,
       vector_dimension, access_count, last_accessed_at, created_at, updated_at
FROM embedding_cache
WHERE text_hash = ?
  AND embedding_model = ?
LIMIT 1
`

type FindCacheByHashParams struct {
	TextHash       string `json:"text_hash"`
	EmbeddingModel string `json:"embedding_model"`
}

func (q *Queries) FindCacheByHash(ctx context.Context, arg FindCacheByHashParams) (EmbeddingCache, error) {
	row := q.db.QueryRowContext(ctx, findCacheByHash, arg.TextHash, arg.EmbeddingModel)
	var i EmbeddingCache
	err := row.Scan(
		&i.ID,
		&i.TextHash,
		&i.TextPreview,
		&i.TextLength,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.VectorDimension,
		&i.AccessCount,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findCachesByHashes = `-- name: FindCachesByHashes :many
SELECT id, text_hash, text_preview, text_length, embedding, embedding_model,
       vector_dimension, access_count, last_accessed_at, created_at, updated_at
FROM embedding_cache
WHERE text_hash IN (/*SLICE:text_hashes*/?)
  AND embedding_model = ?
`

type FindCachesByHashesParams struct {
	TextHashes     []string `json:"text_hashes"`
	EmbeddingModel string   `json:"embedding_model"`
}

func (q *Queries) FindCachesByHashes(ctx context.Context, arg FindCachesByHashesParams) ([]EmbeddingCache, error) {
	query := findCachesByHashes
	var queryParams []interface{}
	if len(arg.TextHashes) > 0 {
		for _, v := range arg.TextHashes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:text_hashes*/?", strings.Repeat(",?", len(arg.TextHashes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:text_hashes*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.EmbeddingModel)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbeddingCache{}
	for rows.Next() {
		var i EmbeddingCache
		if err := rows.Scan(
			&i.ID,
			&i.TextHash,
			&i.TextPreview,
			&i.TextLength,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.VectorDimension,
			&i.AccessCount,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCachesByModel = `-- name: GetCachesByModel :many
SELECT id, text_hash, text_preview, text_length, embedding, embedding_model,
       vector_dimension, access_count, last_accessed_at, created_at, updated_at
FROM embedding_cache
WHERE embedding_model = ?
ORDER BY created_at DESC, id DESC
LIMIT ? OFFSET ?
`

type GetCachesByModelParams struct {
	EmbeddingModel string `json:"embedding_model"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) GetCachesByModel(ctx context.Context, arg GetCachesByModelParams) ([]EmbeddingCache, error) {
	rows, err := q.db.QueryContext(ctx, getCachesByModel, arg.EmbeddingModel, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbeddingCache{}
	for rows.Next() {
		var i EmbeddingCache
		if err := rows.Scan(
			&i.ID,
			&i.TextHash,
			&i.TextPreview,
			&i.TextLength,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.VectorDimension,
			&i.AccessCount,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeastAccessed = `-- name: GetLeastAccessed :many
SELECT id, text_hash, text_preview, text_length, embedding, embedding_model,
       vector_dimension, access_count, last_accessed_at, created_at, updated_at
FROM embedding_cache
ORDER BY last_accessed_at ASC, access_count ASC
LIMIT ?
`

func (q *Queries) GetLeastAccessed(ctx context.Context, limit int32) ([]EmbeddingCache, error) {
	rows, err := q.db.QueryContext(ctx, getLeastAccessed, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbeddingCache{}
	for rows.Next() {
		var i EmbeddingCache
		if err := rows.Scan(
			&i.ID,
			&i.TextHash,
			&i.TextPreview,
			&i.TextLength,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.VectorDimension,
			&i.AccessCount,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEmbeddingCache = `-- name: InsertEmbeddingCache :execresult
INSERT INTO embedding_cache (
  text_hash, text_preview, text_length, embedding, embedding_model,
  vector_dimension, access_count, last_accessed_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEmbeddingCacheParams struct {
	TextHash        string          `json:"text_hash"`
	TextPreview     string          `json:"text_preview"`
	TextLength      int32           `json:"text_length"`
	Embedding       json.RawMessage `json:"embedding"`
	EmbeddingModel  string          `json:"embedding_model"`
	VectorDimension int32           `json:"vector_dimension"`
	AccessCount     int32           `json:"access_count"`
	LastAccessedAt  time.Time       `json:"last_accessed_at"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

func (q *Queries) InsertEmbeddingCache(ctx context.Context, arg InsertEmbeddingCacheParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertEmbeddingCache,
		arg.TextHash,
		arg.TextPreview,
		arg.TextLength,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.VectorDimension,
		arg.AccessCount,
		arg.LastAccessedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertEmbeddingCacheIgnore = `-- name: InsertEmbeddingCacheIgnore :execresult
INSERT IGNORE INTO embedding_cache (
  text_hash, text_preview, text_length, embedding, embedding_model,
  vector_dimension, access_count, last_accessed_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEmbeddingCacheIgnoreParams struct {
	TextHash        string          `json:"text_hash"`
	TextPreview     string          `json:"text_preview"`
	TextLength      int32           `json:"text_length"`
	Embedding       json.RawMessage `json:"embedding"`
	EmbeddingModel  string          `json:"embedding_model"`
	VectorDimension int32           `json:"vector_dimension"`
	AccessCount     int32           `json:"access_count"`
	LastAccessedAt  time.Time       `json:"last_accessed_at"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

func (q *Queries) InsertEmbeddingCacheIgnore(ctx context.Context, arg InsertEmbeddingCacheIgnoreParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertEmbeddingCacheIgnore,
		arg.TextHash,
		arg.TextPreview,
		arg.TextLength,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.VectorDimension,
		arg.AccessCount,
		arg.LastAccessedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const modelStats = `-- name: ModelStats :many
SELECT embedding_model, COUNT(*) AS count
FROM embedding_cache
GROUP BY embedding_model
`

type ModelStatsRow struct {
	EmbeddingModel string `json:"embedding_model"`
	Count          int64  `json:"count"`
}

func (q *Queries) ModelStats(ctx context.Context) ([]ModelStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, modelStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelStatsRow{}
	for rows.Next() {
		var i ModelStatsRow
		if err := rows.Scan(&i.EmbeddingModel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccessByID = `-- name: UpdateAccessByID :exec
UPDATE embedding_cache
SET access_count = access_count + 1,
    last_accessed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateAccessByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateAccessByID, id)
	return err
}

const updateAccessByIDs = `-- name: UpdateAccessByIDs :exec
UPDATE embedding_cache
SET access_count = access_count + 1,
    last_accessed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) UpdateAccessByIDs(ctx context.Context, ids []int64) error {
	query := updateAccessByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const upsertOCRCache = `-- name: UpsertOCRCache :execresult
INSERT INTO embedding_cache (
  text_hash, text_preview, text_length, embedding, embedding_model,
  vector_dimension, access_count, last_accessed_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  text_preview = VALUES(text_preview),
  text_length = VALUES(text_length),
  embedding = VALUES(embedding),
  vector_dimension = VALUES(vector_dimension),
  access_count = access_count + 1,
  last_accessed_at = VALUES(last_accessed_at),
  updated_at = VALUES(updated_at)
`

type UpsertOCRCacheParams struct {
	TextHash        string          `json:"text_hash"`
	TextPreview     string          `json:"text_preview"`
	TextLength      int32           `json:"text_length"`
	Embedding       json.RawMessage `json:"embedding"`
	EmbeddingModel  string          `json:"embedding_model"`
	VectorDimension int32           `json:"vector_dimension"`
	AccessCount     int32           `json:"access_count"`
	LastAccessedAt  time.Time       `json:"last_accessed_at"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

func (q *Queries) UpsertOCRCache(ctx context.Context, arg UpsertOCRCacheParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertOCRCache,
		arg.TextHash,
		arg.TextPreview,
		arg.TextLength,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.VectorDimension,
		arg.AccessCount,
		arg.LastAccessedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}
