// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fragment.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const backfillFragmentDocumentCodeByIDs = `-- name: BackfillFragmentDocumentCodeByIDs :execrows
UPDATE magic_flow_knowledge_fragment
SET document_code = ?,
    updated_at = ?
WHERE deleted_at IS NULL
  AND (document_code = '' OR document_code IS NULL)
  AND id IN (/*SLICE:ids*/?)
`

type BackfillFragmentDocumentCodeByIDsParams struct {
	DocumentCode string    `json:"document_code"`
	UpdatedAt    time.Time `json:"updated_at"`
	Ids          []int64   `json:"ids"`
}

func (q *Queries) BackfillFragmentDocumentCodeByIDs(ctx context.Context, arg BackfillFragmentDocumentCodeByIDsParams) (int64, error) {
	query := backfillFragmentDocumentCodeByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.DocumentCode)
	queryParams = append(queryParams, arg.UpdatedAt)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const backfillFragmentDocumentCodeByThirdFile = `-- name: BackfillFragmentDocumentCodeByThirdFile :execrows
UPDATE magic_flow_knowledge_fragment
SET document_code = ?,
    updated_at = ?
WHERE deleted_at IS NULL
  AND (document_code = '' OR document_code IS NULL)
  AND knowledge_code = ?
  AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.file_id')) = CAST(? AS CHAR(255))
`

type BackfillFragmentDocumentCodeByThirdFileParams struct {
	DocumentCode  string      `json:"document_code"`
	UpdatedAt     time.Time   `json:"updated_at"`
	KnowledgeCode string      `json:"knowledge_code"`
	ThirdFileID   interface{} `json:"third_file_id"`
}

func (q *Queries) BackfillFragmentDocumentCodeByThirdFile(ctx context.Context, arg BackfillFragmentDocumentCodeByThirdFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, backfillFragmentDocumentCodeByThirdFile,
		arg.DocumentCode,
		arg.UpdatedAt,
		arg.KnowledgeCode,
		arg.ThirdFileID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countFragmentStatsByKnowledgeBase = `-- name: CountFragmentStatsByKnowledgeBase :one
SELECT
	COUNT(*) AS fragment_count,
	COALESCE(SUM(CASE WHEN sync_status = ? THEN 1 ELSE 0 END), 0) AS synced_v2_count,
	COALESCE(SUM(CASE WHEN sync_status = ? THEN 1 ELSE 0 END), 0) AS synced_v1_count
FROM magic_flow_knowledge_fragment
WHERE knowledge_code = ?
  AND deleted_at IS NULL
`

type CountFragmentStatsByKnowledgeBaseParams struct {
	SyncStatus    int32  `json:"sync_status"`
	SyncStatus_2  int32  `json:"sync_status_2"`
	KnowledgeCode string `json:"knowledge_code"`
}

type CountFragmentStatsByKnowledgeBaseRow struct {
	FragmentCount int64       `json:"fragment_count"`
	SyncedV2Count interface{} `json:"synced_v2_count"`
	SyncedV1Count interface{} `json:"synced_v1_count"`
}

func (q *Queries) CountFragmentStatsByKnowledgeBase(ctx context.Context, arg CountFragmentStatsByKnowledgeBaseParams) (CountFragmentStatsByKnowledgeBaseRow, error) {
	row := q.db.QueryRowContext(ctx, countFragmentStatsByKnowledgeBase, arg.SyncStatus, arg.SyncStatus_2, arg.KnowledgeCode)
	var i CountFragmentStatsByKnowledgeBaseRow
	err := row.Scan(&i.FragmentCount, &i.SyncedV2Count, &i.SyncedV1Count)
	return i, err
}

const countFragmentStatsByKnowledgeBases = `-- name: CountFragmentStatsByKnowledgeBases :many
SELECT
	knowledge_code,
	COUNT(*) AS fragment_count,
	COALESCE(SUM(CASE WHEN sync_status = ? THEN 1 ELSE 0 END), 0) AS synced_v2_count,
	COALESCE(SUM(CASE WHEN sync_status = ? THEN 1 ELSE 0 END), 0) AS synced_v1_count
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND knowledge_code IN (/*SLICE:knowledge_codes*/?)
GROUP BY knowledge_code
ORDER BY knowledge_code ASC
`

type CountFragmentStatsByKnowledgeBasesParams struct {
	SyncStatus     int32    `json:"sync_status"`
	SyncStatus_2   int32    `json:"sync_status_2"`
	KnowledgeCodes []string `json:"knowledge_codes"`
}

type CountFragmentStatsByKnowledgeBasesRow struct {
	KnowledgeCode string      `json:"knowledge_code"`
	FragmentCount int64       `json:"fragment_count"`
	SyncedV2Count interface{} `json:"synced_v2_count"`
	SyncedV1Count interface{} `json:"synced_v1_count"`
}

func (q *Queries) CountFragmentStatsByKnowledgeBases(ctx context.Context, arg CountFragmentStatsByKnowledgeBasesParams) ([]CountFragmentStatsByKnowledgeBasesRow, error) {
	query := countFragmentStatsByKnowledgeBases
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SyncStatus)
	queryParams = append(queryParams, arg.SyncStatus_2)
	if len(arg.KnowledgeCodes) > 0 {
		for _, v := range arg.KnowledgeCodes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:knowledge_codes*/?", strings.Repeat(",?", len(arg.KnowledgeCodes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:knowledge_codes*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFragmentStatsByKnowledgeBasesRow{}
	for rows.Next() {
		var i CountFragmentStatsByKnowledgeBasesRow
		if err := rows.Scan(
			&i.KnowledgeCode,
			&i.FragmentCount,
			&i.SyncedV2Count,
			&i.SyncedV1Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFragmentsByKnowledge = `-- name: CountFragmentsByKnowledge :one
SELECT COUNT(*)
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND knowledge_code = ?
  AND content LIKE ?
  AND sync_status IN (/*SLICE:sync_status_values*/?)
`

type CountFragmentsByKnowledgeParams struct {
	KnowledgeCode    string  `json:"knowledge_code"`
	ContentLike      string  `json:"content_like"`
	SyncStatusValues []int32 `json:"sync_status_values"`
}

func (q *Queries) CountFragmentsByKnowledge(ctx context.Context, arg CountFragmentsByKnowledgeParams) (int64, error) {
	query := countFragmentsByKnowledge
	var queryParams []interface{}
	queryParams = append(queryParams, arg.KnowledgeCode)
	queryParams = append(queryParams, arg.ContentLike)
	if len(arg.SyncStatusValues) > 0 {
		for _, v := range arg.SyncStatusValues {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", strings.Repeat(",?", len(arg.SyncStatusValues))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFragmentsByKnowledgeAndBusinessID = `-- name: CountFragmentsByKnowledgeAndBusinessID :one
SELECT COUNT(*)
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND knowledge_code = ?
  AND business_id = ?
  AND content LIKE ?
  AND sync_status IN (/*SLICE:sync_status_values*/?)
`

type CountFragmentsByKnowledgeAndBusinessIDParams struct {
	KnowledgeCode    string  `json:"knowledge_code"`
	BusinessID       string  `json:"business_id"`
	ContentLike      string  `json:"content_like"`
	SyncStatusValues []int32 `json:"sync_status_values"`
}

func (q *Queries) CountFragmentsByKnowledgeAndBusinessID(ctx context.Context, arg CountFragmentsByKnowledgeAndBusinessIDParams) (int64, error) {
	query := countFragmentsByKnowledgeAndBusinessID
	var queryParams []interface{}
	queryParams = append(queryParams, arg.KnowledgeCode)
	queryParams = append(queryParams, arg.BusinessID)
	queryParams = append(queryParams, arg.ContentLike)
	if len(arg.SyncStatusValues) > 0 {
		for _, v := range arg.SyncStatusValues {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", strings.Repeat(",?", len(arg.SyncStatusValues))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFragmentsByKnowledgeAndDocument = `-- name: CountFragmentsByKnowledgeAndDocument :one
SELECT COUNT(*)
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND knowledge_code = ?
  AND document_code = ?
`

type CountFragmentsByKnowledgeAndDocumentParams struct {
	KnowledgeCode string `json:"knowledge_code"`
	DocumentCode  string `json:"document_code"`
}

func (q *Queries) CountFragmentsByKnowledgeAndDocument(ctx context.Context, arg CountFragmentsByKnowledgeAndDocumentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFragmentsByKnowledgeAndDocument, arg.KnowledgeCode, arg.DocumentCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFragmentsByKnowledgeAndDocumentFiltered = `-- name: CountFragmentsByKnowledgeAndDocumentFiltered :one
SELECT COUNT(*)
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND knowledge_code = ?
  AND document_code = ?
  AND content LIKE ?
  AND sync_status IN (/*SLICE:sync_status_values*/?)
`

type CountFragmentsByKnowledgeAndDocumentFilteredParams struct {
	KnowledgeCode    string  `json:"knowledge_code"`
	DocumentCode     string  `json:"document_code"`
	ContentLike      string  `json:"content_like"`
	SyncStatusValues []int32 `json:"sync_status_values"`
}

func (q *Queries) CountFragmentsByKnowledgeAndDocumentFiltered(ctx context.Context, arg CountFragmentsByKnowledgeAndDocumentFilteredParams) (int64, error) {
	query := countFragmentsByKnowledgeAndDocumentFiltered
	var queryParams []interface{}
	queryParams = append(queryParams, arg.KnowledgeCode)
	queryParams = append(queryParams, arg.DocumentCode)
	queryParams = append(queryParams, arg.ContentLike)
	if len(arg.SyncStatusValues) > 0 {
		for _, v := range arg.SyncStatusValues {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", strings.Repeat(",?", len(arg.SyncStatusValues))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFragmentsByKnowledgeBase = `-- name: CountFragmentsByKnowledgeBase :one
SELECT COUNT(*)
FROM magic_flow_knowledge_fragment
WHERE knowledge_code = ?
  AND deleted_at IS NULL
`

func (q *Queries) CountFragmentsByKnowledgeBase(ctx context.Context, knowledgeCode string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFragmentsByKnowledgeBase, knowledgeCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSyncedFragmentsByKnowledgeBase = `-- name: CountSyncedFragmentsByKnowledgeBase :one
SELECT COUNT(*)
FROM magic_flow_knowledge_fragment
WHERE knowledge_code = ?
  AND sync_status = ?
  AND deleted_at IS NULL
`

type CountSyncedFragmentsByKnowledgeBaseParams struct {
	KnowledgeCode string `json:"knowledge_code"`
	SyncStatus    int32  `json:"sync_status"`
}

func (q *Queries) CountSyncedFragmentsByKnowledgeBase(ctx context.Context, arg CountSyncedFragmentsByKnowledgeBaseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSyncedFragmentsByKnowledgeBase, arg.KnowledgeCode, arg.SyncStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFragmentByID = `-- name: DeleteFragmentByID :execrows
DELETE FROM magic_flow_knowledge_fragment
WHERE id = ?
`

func (q *Queries) DeleteFragmentByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFragmentByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFragmentsByDocument = `-- name: DeleteFragmentsByDocument :execrows
DELETE FROM magic_flow_knowledge_fragment
WHERE knowledge_code = ?
  AND document_code = ?
`

type DeleteFragmentsByDocumentParams struct {
	KnowledgeCode string `json:"knowledge_code"`
	DocumentCode  string `json:"document_code"`
}

func (q *Queries) DeleteFragmentsByDocument(ctx context.Context, arg DeleteFragmentsByDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFragmentsByDocument, arg.KnowledgeCode, arg.DocumentCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFragmentsByDocumentCodes = `-- name: DeleteFragmentsByDocumentCodes :execrows
DELETE FROM magic_flow_knowledge_fragment
WHERE knowledge_code = ?
  AND document_code IN (/*SLICE:document_codes*/?)
`

type DeleteFragmentsByDocumentCodesParams struct {
	KnowledgeCode string   `json:"knowledge_code"`
	DocumentCodes []string `json:"document_codes"`
}

func (q *Queries) DeleteFragmentsByDocumentCodes(ctx context.Context, arg DeleteFragmentsByDocumentCodesParams) (int64, error) {
	query := deleteFragmentsByDocumentCodes
	var queryParams []interface{}
	queryParams = append(queryParams, arg.KnowledgeCode)
	if len(arg.DocumentCodes) > 0 {
		for _, v := range arg.DocumentCodes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:document_codes*/?", strings.Repeat(",?", len(arg.DocumentCodes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:document_codes*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFragmentsByIDs = `-- name: DeleteFragmentsByIDs :execrows
DELETE FROM magic_flow_knowledge_fragment
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteFragmentsByIDs(ctx context.Context, ids []int64) (int64, error) {
	query := deleteFragmentsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFragmentsByKnowledgeBase = `-- name: DeleteFragmentsByKnowledgeBase :execrows
DELETE FROM magic_flow_knowledge_fragment
WHERE knowledge_code = ?
`

func (q *Queries) DeleteFragmentsByKnowledgeBase(ctx context.Context, knowledgeCode string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFragmentsByKnowledgeBase, knowledgeCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findFragmentByID = `-- name: FindFragmentByID :one
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) FindFragmentByID(ctx context.Context, id int64) (MagicFlowKnowledgeFragment, error) {
	row := q.db.QueryRowContext(ctx, findFragmentByID, id)
	var i MagicFlowKnowledgeFragment
	err := row.Scan(
		&i.ID,
		&i.KnowledgeCode,
		&i.DocumentCode,
		&i.ParentFragmentID,
		&i.Version,
		&i.Content,
		&i.Metadata,
		&i.BusinessID,
		&i.SyncStatus,
		&i.SyncTimes,
		&i.SyncStatusMessage,
		&i.PointID,
		&i.Vector,
		&i.WordCount,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findFragmentsByIDs = `-- name: FindFragmentsByIDs :many
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND id IN (/*SLICE:ids*/?)
ORDER BY id ASC
`

func (q *Queries) FindFragmentsByIDs(ctx context.Context, ids []int64) ([]MagicFlowKnowledgeFragment, error) {
	query := findFragmentsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicFlowKnowledgeFragment{}
	for rows.Next() {
		var i MagicFlowKnowledgeFragment
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeCode,
			&i.DocumentCode,
			&i.ParentFragmentID,
			&i.Version,
			&i.Content,
			&i.Metadata,
			&i.BusinessID,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.PointID,
			&i.Vector,
			&i.WordCount,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFragmentsByPointIDs = `-- name: FindFragmentsByPointIDs :many
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND point_id IN (/*SLICE:point_ids*/?)
ORDER BY id ASC
`

func (q *Queries) FindFragmentsByPointIDs(ctx context.Context, pointIds []string) ([]MagicFlowKnowledgeFragment, error) {
	query := findFragmentsByPointIDs
	var queryParams []interface{}
	if len(pointIds) > 0 {
		for _, v := range pointIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:point_ids*/?", strings.Repeat(",?", len(pointIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:point_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicFlowKnowledgeFragment{}
	for rows.Next() {
		var i MagicFlowKnowledgeFragment
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeCode,
			&i.DocumentCode,
			&i.ParentFragmentID,
			&i.Version,
			&i.Content,
			&i.Metadata,
			&i.BusinessID,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.PointID,
			&i.Vector,
			&i.WordCount,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFragment = `-- name: InsertFragment :execresult
INSERT INTO magic_flow_knowledge_fragment (
  knowledge_code, document_code, content, metadata, business_id,
  sync_status, sync_times, sync_status_message, point_id, word_count,
  created_uid, updated_uid, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertFragmentParams struct {
	KnowledgeCode     string    `json:"knowledge_code"`
	DocumentCode      string    `json:"document_code"`
	Content           string    `json:"content"`
	Metadata          []byte    `json:"metadata"`
	BusinessID        string    `json:"business_id"`
	SyncStatus        int32     `json:"sync_status"`
	SyncTimes         int32     `json:"sync_times"`
	SyncStatusMessage string    `json:"sync_status_message"`
	PointID           string    `json:"point_id"`
	WordCount         uint64    `json:"word_count"`
	CreatedUid        string    `json:"created_uid"`
	UpdatedUid        string    `json:"updated_uid"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) InsertFragment(ctx context.Context, arg InsertFragmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertFragment,
		arg.KnowledgeCode,
		arg.DocumentCode,
		arg.Content,
		arg.Metadata,
		arg.BusinessID,
		arg.SyncStatus,
		arg.SyncTimes,
		arg.SyncStatusMessage,
		arg.PointID,
		arg.WordCount,
		arg.CreatedUid,
		arg.UpdatedUid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const listFragmentsByKnowledge = `-- name: ListFragmentsByKnowledge :many
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND knowledge_code = ?
  AND content LIKE ?
  AND sync_status IN (/*SLICE:sync_status_values*/?)
ORDER BY id ASC
LIMIT ? OFFSET ?
`

type ListFragmentsByKnowledgeParams struct {
	KnowledgeCode    string  `json:"knowledge_code"`
	ContentLike      string  `json:"content_like"`
	SyncStatusValues []int32 `json:"sync_status_values"`
	Limit            int32   `json:"limit"`
	Offset           int32   `json:"offset"`
}

func (q *Queries) ListFragmentsByKnowledge(ctx context.Context, arg ListFragmentsByKnowledgeParams) ([]MagicFlowKnowledgeFragment, error) {
	query := listFragmentsByKnowledge
	var queryParams []interface{}
	queryParams = append(queryParams, arg.KnowledgeCode)
	queryParams = append(queryParams, arg.ContentLike)
	if len(arg.SyncStatusValues) > 0 {
		for _, v := range arg.SyncStatusValues {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", strings.Repeat(",?", len(arg.SyncStatusValues))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicFlowKnowledgeFragment{}
	for rows.Next() {
		var i MagicFlowKnowledgeFragment
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeCode,
			&i.DocumentCode,
			&i.ParentFragmentID,
			&i.Version,
			&i.Content,
			&i.Metadata,
			&i.BusinessID,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.PointID,
			&i.Vector,
			&i.WordCount,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentsByKnowledgeAndBusinessID = `-- name: ListFragmentsByKnowledgeAndBusinessID :many
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND knowledge_code = ?
  AND business_id = ?
  AND content LIKE ?
  AND sync_status IN (/*SLICE:sync_status_values*/?)
ORDER BY id ASC
LIMIT ? OFFSET ?
`

type ListFragmentsByKnowledgeAndBusinessIDParams struct {
	KnowledgeCode    string  `json:"knowledge_code"`
	BusinessID       string  `json:"business_id"`
	ContentLike      string  `json:"content_like"`
	SyncStatusValues []int32 `json:"sync_status_values"`
	Limit            int32   `json:"limit"`
	Offset           int32   `json:"offset"`
}

func (q *Queries) ListFragmentsByKnowledgeAndBusinessID(ctx context.Context, arg ListFragmentsByKnowledgeAndBusinessIDParams) ([]MagicFlowKnowledgeFragment, error) {
	query := listFragmentsByKnowledgeAndBusinessID
	var queryParams []interface{}
	queryParams = append(queryParams, arg.KnowledgeCode)
	queryParams = append(queryParams, arg.BusinessID)
	queryParams = append(queryParams, arg.ContentLike)
	if len(arg.SyncStatusValues) > 0 {
		for _, v := range arg.SyncStatusValues {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", strings.Repeat(",?", len(arg.SyncStatusValues))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicFlowKnowledgeFragment{}
	for rows.Next() {
		var i MagicFlowKnowledgeFragment
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeCode,
			&i.DocumentCode,
			&i.ParentFragmentID,
			&i.Version,
			&i.Content,
			&i.Metadata,
			&i.BusinessID,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.PointID,
			&i.Vector,
			&i.WordCount,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentsByKnowledgeAndDocument = `-- name: ListFragmentsByKnowledgeAndDocument :many
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND knowledge_code = ?
  AND document_code = ?
ORDER BY id ASC
LIMIT ? OFFSET ?
`

type ListFragmentsByKnowledgeAndDocumentParams struct {
	KnowledgeCode string `json:"knowledge_code"`
	DocumentCode  string `json:"document_code"`
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
}

func (q *Queries) ListFragmentsByKnowledgeAndDocument(ctx context.Context, arg ListFragmentsByKnowledgeAndDocumentParams) ([]MagicFlowKnowledgeFragment, error) {
	rows, err := q.db.QueryContext(ctx, listFragmentsByKnowledgeAndDocument,
		arg.KnowledgeCode,
		arg.DocumentCode,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicFlowKnowledgeFragment{}
	for rows.Next() {
		var i MagicFlowKnowledgeFragment
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeCode,
			&i.DocumentCode,
			&i.ParentFragmentID,
			&i.Version,
			&i.Content,
			&i.Metadata,
			&i.BusinessID,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.PointID,
			&i.Vector,
			&i.WordCount,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentsByKnowledgeAndDocumentAfterID = `-- name: ListFragmentsByKnowledgeAndDocumentAfterID :many
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND knowledge_code = ?
  AND document_code = ?
  AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListFragmentsByKnowledgeAndDocumentAfterIDParams struct {
	KnowledgeCode string `json:"knowledge_code"`
	DocumentCode  string `json:"document_code"`
	ID            int64  `json:"id"`
	Limit         int32  `json:"limit"`
}

func (q *Queries) ListFragmentsByKnowledgeAndDocumentAfterID(ctx context.Context, arg ListFragmentsByKnowledgeAndDocumentAfterIDParams) ([]MagicFlowKnowledgeFragment, error) {
	rows, err := q.db.QueryContext(ctx, listFragmentsByKnowledgeAndDocumentAfterID,
		arg.KnowledgeCode,
		arg.DocumentCode,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicFlowKnowledgeFragment{}
	for rows.Next() {
		var i MagicFlowKnowledgeFragment
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeCode,
			&i.DocumentCode,
			&i.ParentFragmentID,
			&i.Version,
			&i.Content,
			&i.Metadata,
			&i.BusinessID,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.PointID,
			&i.Vector,
			&i.WordCount,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentsByKnowledgeAndDocumentFiltered = `-- name: ListFragmentsByKnowledgeAndDocumentFiltered :many
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND knowledge_code = ?
  AND document_code = ?
  AND content LIKE ?
  AND sync_status IN (/*SLICE:sync_status_values*/?)
ORDER BY id ASC
LIMIT ? OFFSET ?
`

type ListFragmentsByKnowledgeAndDocumentFilteredParams struct {
	KnowledgeCode    string  `json:"knowledge_code"`
	DocumentCode     string  `json:"document_code"`
	ContentLike      string  `json:"content_like"`
	SyncStatusValues []int32 `json:"sync_status_values"`
	Limit            int32   `json:"limit"`
	Offset           int32   `json:"offset"`
}

func (q *Queries) ListFragmentsByKnowledgeAndDocumentFiltered(ctx context.Context, arg ListFragmentsByKnowledgeAndDocumentFilteredParams) ([]MagicFlowKnowledgeFragment, error) {
	query := listFragmentsByKnowledgeAndDocumentFiltered
	var queryParams []interface{}
	queryParams = append(queryParams, arg.KnowledgeCode)
	queryParams = append(queryParams, arg.DocumentCode)
	queryParams = append(queryParams, arg.ContentLike)
	if len(arg.SyncStatusValues) > 0 {
		for _, v := range arg.SyncStatusValues {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", strings.Repeat(",?", len(arg.SyncStatusValues))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:sync_status_values*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicFlowKnowledgeFragment{}
	for rows.Next() {
		var i MagicFlowKnowledgeFragment
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeCode,
			&i.DocumentCode,
			&i.ParentFragmentID,
			&i.Version,
			&i.Content,
			&i.Metadata,
			&i.BusinessID,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.PointID,
			&i.Vector,
			&i.WordCount,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentsMissingDocumentCodeByKnowledge = `-- name: ListFragmentsMissingDocumentCodeByKnowledge :many
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND (document_code = '' OR document_code IS NULL)
  AND knowledge_code = ?
  AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListFragmentsMissingDocumentCodeByKnowledgeParams struct {
	KnowledgeCode string `json:"knowledge_code"`
	StartID       int64  `json:"start_id"`
	Limit         int32  `json:"limit"`
}

func (q *Queries) ListFragmentsMissingDocumentCodeByKnowledge(ctx context.Context, arg ListFragmentsMissingDocumentCodeByKnowledgeParams) ([]MagicFlowKnowledgeFragment, error) {
	rows, err := q.db.QueryContext(ctx, listFragmentsMissingDocumentCodeByKnowledge, arg.KnowledgeCode, arg.StartID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicFlowKnowledgeFragment{}
	for rows.Next() {
		var i MagicFlowKnowledgeFragment
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeCode,
			&i.DocumentCode,
			&i.ParentFragmentID,
			&i.Version,
			&i.Content,
			&i.Metadata,
			&i.BusinessID,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.PointID,
			&i.Vector,
			&i.WordCount,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFragmentsMissingDocumentCodeByKnowledgeCodes = `-- name: ListFragmentsMissingDocumentCodeByKnowledgeCodes :many
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND (document_code = '' OR document_code IS NULL)
  AND knowledge_code IN (/*SLICE:knowledge_codes*/?)
  AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListFragmentsMissingDocumentCodeByKnowledgeCodesParams struct {
	KnowledgeCodes []string `json:"knowledge_codes"`
	StartID        int64    `json:"start_id"`
	Limit          int32    `json:"limit"`
}

func (q *Queries) ListFragmentsMissingDocumentCodeByKnowledgeCodes(ctx context.Context, arg ListFragmentsMissingDocumentCodeByKnowledgeCodesParams) ([]MagicFlowKnowledgeFragment, error) {
	query := listFragmentsMissingDocumentCodeByKnowledgeCodes
	var queryParams []interface{}
	if len(arg.KnowledgeCodes) > 0 {
		for _, v := range arg.KnowledgeCodes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:knowledge_codes*/?", strings.Repeat(",?", len(arg.KnowledgeCodes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:knowledge_codes*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.StartID)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicFlowKnowledgeFragment{}
	for rows.Next() {
		var i MagicFlowKnowledgeFragment
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeCode,
			&i.DocumentCode,
			&i.ParentFragmentID,
			&i.Version,
			&i.Content,
			&i.Metadata,
			&i.BusinessID,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.PointID,
			&i.Vector,
			&i.WordCount,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFragments = `-- name: ListPendingFragments :many
SELECT id, knowledge_code, document_code, parent_fragment_id, version, content, metadata, business_id, sync_status, sync_times, sync_status_message, point_id, vector, word_count, created_uid, updated_uid, created_at, updated_at, deleted_at
FROM magic_flow_knowledge_fragment
WHERE knowledge_code = ?
  AND sync_status IN (?, ?)
  AND deleted_at IS NULL
ORDER BY id ASC
LIMIT ?
`

type ListPendingFragmentsParams struct {
	KnowledgeCode string `json:"knowledge_code"`
	SyncStatus    int32  `json:"sync_status"`
	SyncStatus_2  int32  `json:"sync_status_2"`
	Limit         int32  `json:"limit"`
}

func (q *Queries) ListPendingFragments(ctx context.Context, arg ListPendingFragmentsParams) ([]MagicFlowKnowledgeFragment, error) {
	rows, err := q.db.QueryContext(ctx, listPendingFragments,
		arg.KnowledgeCode,
		arg.SyncStatus,
		arg.SyncStatus_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MagicFlowKnowledgeFragment{}
	for rows.Next() {
		var i MagicFlowKnowledgeFragment
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeCode,
			&i.DocumentCode,
			&i.ParentFragmentID,
			&i.Version,
			&i.Content,
			&i.Metadata,
			&i.BusinessID,
			&i.SyncStatus,
			&i.SyncTimes,
			&i.SyncStatusMessage,
			&i.PointID,
			&i.Vector,
			&i.WordCount,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThirdFileRepairGroupsByKnowledgeCodes = `-- name: ListThirdFileRepairGroupsByKnowledgeCodes :many
SELECT knowledge_code,
       JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.file_id')) AS third_file_id,
       COALESCE(MIN(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.knowledge_base_id')), '')), '') AS knowledge_base_id,
       COALESCE(
         MIN(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.group_ref')), '')),
         MIN(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.folder_id')), '')),
         MIN(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.parent_id')), '')),
         ''
       ) AS group_ref,
       COALESCE(MIN(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.third_file_type')), '')), '') AS third_file_type,
       COALESCE(MIN(NULLIF(document_code, '')), '') AS document_code,
       COALESCE(MIN(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.document_name')), '')), '') AS document_name,
       COALESCE(MIN(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.url')), '')), '') AS preview_url,
       COALESCE(MIN(NULLIF(created_uid, '')), '') AS created_uid,
       COALESCE(MIN(NULLIF(updated_uid, '')), '') AS updated_uid,
       COUNT(*) AS fragment_count,
       COALESCE(SUM(CASE WHEN document_code = '' OR document_code IS NULL THEN 1 ELSE 0 END), 0) AS missing_document_code_count
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.file_id')) <> ''
  AND knowledge_code IN (/*SLICE:knowledge_codes*/?)
GROUP BY knowledge_code, JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.file_id'))
ORDER BY knowledge_code ASC, third_file_id ASC
LIMIT ? OFFSET ?
`

type ListThirdFileRepairGroupsByKnowledgeCodesParams struct {
	KnowledgeCodes []string `json:"knowledge_codes"`
	Limit          int32    `json:"limit"`
	Offset         int32    `json:"offset"`
}

type ListThirdFileRepairGroupsByKnowledgeCodesRow struct {
	KnowledgeCode            string      `json:"knowledge_code"`
	ThirdFileID              []byte      `json:"third_file_id"`
	KnowledgeBaseID          interface{} `json:"knowledge_base_id"`
	GroupRef                 interface{} `json:"group_ref"`
	ThirdFileType            interface{} `json:"third_file_type"`
	DocumentCode             interface{} `json:"document_code"`
	DocumentName             interface{} `json:"document_name"`
	PreviewUrl               interface{} `json:"preview_url"`
	CreatedUid               interface{} `json:"created_uid"`
	UpdatedUid               interface{} `json:"updated_uid"`
	FragmentCount            int64       `json:"fragment_count"`
	MissingDocumentCodeCount interface{} `json:"missing_document_code_count"`
}

func (q *Queries) ListThirdFileRepairGroupsByKnowledgeCodes(ctx context.Context, arg ListThirdFileRepairGroupsByKnowledgeCodesParams) ([]ListThirdFileRepairGroupsByKnowledgeCodesRow, error) {
	query := listThirdFileRepairGroupsByKnowledgeCodes
	var queryParams []interface{}
	if len(arg.KnowledgeCodes) > 0 {
		for _, v := range arg.KnowledgeCodes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:knowledge_codes*/?", strings.Repeat(",?", len(arg.KnowledgeCodes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:knowledge_codes*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThirdFileRepairGroupsByKnowledgeCodesRow{}
	for rows.Next() {
		var i ListThirdFileRepairGroupsByKnowledgeCodesRow
		if err := rows.Scan(
			&i.KnowledgeCode,
			&i.ThirdFileID,
			&i.KnowledgeBaseID,
			&i.GroupRef,
			&i.ThirdFileType,
			&i.DocumentCode,
			&i.DocumentName,
			&i.PreviewUrl,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.FragmentCount,
			&i.MissingDocumentCodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThirdFileRepairKnowledgeCodes = `-- name: ListThirdFileRepairKnowledgeCodes :many
SELECT DISTINCT knowledge_code
FROM magic_flow_knowledge_fragment
WHERE deleted_at IS NULL
  AND JSON_UNQUOTE(JSON_EXTRACT(metadata, '$.file_id')) <> ''
ORDER BY knowledge_code ASC
`

func (q *Queries) ListThirdFileRepairKnowledgeCodes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listThirdFileRepairKnowledgeCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var knowledge_code string
		if err := rows.Scan(&knowledge_code); err != nil {
			return nil, err
		}
		items = append(items, knowledge_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFragment = `-- name: UpdateFragment :execrows
UPDATE magic_flow_knowledge_fragment
SET content = ?,
    metadata = ?,
    point_id = ?,
    word_count = ?,
    sync_status = ?,
    sync_times = ?,
    sync_status_message = ?,
    updated_uid = ?,
    updated_at = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type UpdateFragmentParams struct {
	Content           string    `json:"content"`
	Metadata          []byte    `json:"metadata"`
	PointID           string    `json:"point_id"`
	WordCount         uint64    `json:"word_count"`
	SyncStatus        int32     `json:"sync_status"`
	SyncTimes         int32     `json:"sync_times"`
	SyncStatusMessage string    `json:"sync_status_message"`
	UpdatedUid        string    `json:"updated_uid"`
	UpdatedAt         time.Time `json:"updated_at"`
	ID                int64     `json:"id"`
}

func (q *Queries) UpdateFragment(ctx context.Context, arg UpdateFragmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFragment,
		arg.Content,
		arg.Metadata,
		arg.PointID,
		arg.WordCount,
		arg.SyncStatus,
		arg.SyncTimes,
		arg.SyncStatusMessage,
		arg.UpdatedUid,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFragmentSyncStatus = `-- name: UpdateFragmentSyncStatus :execrows
UPDATE magic_flow_knowledge_fragment
SET sync_status = ?,
    sync_times = ?,
    sync_status_message = ?,
    updated_at = ?
WHERE id = ?
  AND deleted_at IS NULL
`

type UpdateFragmentSyncStatusParams struct {
	SyncStatus        int32     `json:"sync_status"`
	SyncTimes         int32     `json:"sync_times"`
	SyncStatusMessage string    `json:"sync_status_message"`
	UpdatedAt         time.Time `json:"updated_at"`
	ID                int64     `json:"id"`
}

func (q *Queries) UpdateFragmentSyncStatus(ctx context.Context, arg UpdateFragmentSyncStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFragmentSyncStatus,
		arg.SyncStatus,
		arg.SyncTimes,
		arg.SyncStatusMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
