// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: knowledge_base_ingestion.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countEnabledKnowledgeBaseIngestionSources = `-- name: CountEnabledKnowledgeBaseIngestionSources :one
SELECT COUNT(*)
FROM knowledge_base_ingestion_sources
WHERE organization_code = ?
  AND provider = ?
  AND enabled = TRUE
`

type CountEnabledKnowledgeBaseIngestionSourcesParams struct {
	OrganizationCode string `json:"organization_code"`
	Provider         string `json:"provider"`
}

func (q *Queries) CountEnabledKnowledgeBaseIngestionSources(ctx context.Context, arg CountEnabledKnowledgeBaseIngestionSourcesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledKnowledgeBaseIngestionSources, arg.OrganizationCode, arg.Provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKnowledgeBaseIngestionItemsBySourceAndStatus = `-- name: CountKnowledgeBaseIngestionItemsBySourceAndStatus :one
SELECT COUNT(*)
FROM knowledge_base_ingestion_items
WHERE organization_code = ?
  AND provider = ?
  AND source_code = ?
  AND status IN (/*SLICE:statuses*/?)
`

type CountKnowledgeBaseIngestionItemsBySourceAndStatusParams struct {
	OrganizationCode string   `json:"organization_code"`
	Provider         string   `json:"provider"`
	SourceCode       string   `json:"source_code"`
	Statuses         []string `json:"statuses"`
}

func (q *Queries) CountKnowledgeBaseIngestionItemsBySourceAndStatus(ctx context.Context, arg CountKnowledgeBaseIngestionItemsBySourceAndStatusParams) (int64, error) {
	query := countKnowledgeBaseIngestionItemsBySourceAndStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrganizationCode)
	queryParams = append(queryParams, arg.Provider)
	queryParams = append(queryParams, arg.SourceCode)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finishKnowledgeBaseIngestionRun = `-- name: FinishKnowledgeBaseIngestionRun :execrows
UPDATE knowledge_base_ingestion_runs
SET status = ?,
    pulled_count = ?,
    changed_count = ?,
    cleaned_count = ?,
    skipped_count = ?,
    failed_count = ?,
    error_summary = ?,
    finished_at = ?
WHERE id = ?
`

type FinishKnowledgeBaseIngestionRunParams struct {
	Status       string       `json:"status"`
	PulledCount  uint32       `json:"pulled_count"`
	ChangedCount uint32       `json:"changed_count"`
	CleanedCount uint32       `json:"cleaned_count"`
	SkippedCount uint32       `json:"skipped_count"`
	FailedCount  uint32       `json:"failed_count"`
	ErrorSummary string       `json:"error_summary"`
	FinishedAt   sql.NullTime `json:"finished_at"`
	ID           int64        `json:"id"`
}

func (q *Queries) FinishKnowledgeBaseIngestionRun(ctx context.Context, arg FinishKnowledgeBaseIngestionRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishKnowledgeBaseIngestionRun,
		arg.Status,
		arg.PulledCount,
		arg.ChangedCount,
		arg.CleanedCount,
		arg.SkippedCount,
		arg.FailedCount,
		arg.ErrorSummary,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getKnowledgeBaseIngestionItemByRef = `-- name: GetKnowledgeBaseIngestionItemByRef :one
SELECT id, organization_code, provider, source_code, item_ref, item_type, title, source_url, extension, raw_hash, clean_hash, clean_size, cleaner_version, status, snapshot_meta, last_error, last_pulled_at, last_cleaned_at, created_at, updated_at
FROM knowledge_base_ingestion_items
WHERE organization_code = ?
  AND provider = ?
  AND source_code = ?
  AND item_ref = ?
LIMIT 1
`

type GetKnowledgeBaseIngestionItemByRefParams struct {
	OrganizationCode string `json:"organization_code"`
	Provider         string `json:"provider"`
	SourceCode       string `json:"source_code"`
	ItemRef          string `json:"item_ref"`
}

func (q *Queries) GetKnowledgeBaseIngestionItemByRef(ctx context.Context, arg GetKnowledgeBaseIngestionItemByRefParams) (KnowledgeBaseIngestionItem, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeBaseIngestionItemByRef,
		arg.OrganizationCode,
		arg.Provider,
		arg.SourceCode,
		arg.ItemRef,
	)
	var i KnowledgeBaseIngestionItem
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.Provider,
		&i.SourceCode,
		&i.ItemRef,
		&i.ItemType,
		&i.Title,
		&i.SourceUrl,
		&i.Extension,
		&i.RawHash,
		&i.CleanHash,
		&i.CleanSize,
		&i.CleanerVersion,
		&i.Status,
		&i.SnapshotMeta,
		&i.LastError,
		&i.LastPulledAt,
		&i.LastCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKnowledgeBaseIngestionItemContentByItemID = `-- name: GetKnowledgeBaseIngestionItemContentByItemID :one
SELECT item_id, organization_code, provider, source_code, item_ref, clean_hash, content, content_format, content_charset, content_size, created_at, updated_at
FROM knowledge_base_ingestion_item_contents
WHERE item_id = ?
`

func (q *Queries) GetKnowledgeBaseIngestionItemContentByItemID(ctx context.Context, itemID int64) (KnowledgeBaseIngestionItemContent, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeBaseIngestionItemContentByItemID, itemID)
	var i KnowledgeBaseIngestionItemContent
	err := row.Scan(
		&i.ItemID,
		&i.OrganizationCode,
		&i.Provider,
		&i.SourceCode,
		&i.ItemRef,
		&i.CleanHash,
		&i.Content,
		&i.ContentFormat,
		&i.ContentCharset,
		&i.ContentSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKnowledgeBaseIngestionItemContentByRef = `-- name: GetKnowledgeBaseIngestionItemContentByRef :one
SELECT item_id, organization_code, provider, source_code, item_ref, clean_hash, content, content_format, content_charset, content_size, created_at, updated_at
FROM knowledge_base_ingestion_item_contents
WHERE organization_code = ?
  AND provider = ?
  AND source_code = ?
  AND item_ref = ?
LIMIT 1
`

type GetKnowledgeBaseIngestionItemContentByRefParams struct {
	OrganizationCode string `json:"organization_code"`
	Provider         string `json:"provider"`
	SourceCode       string `json:"source_code"`
	ItemRef          string `json:"item_ref"`
}

func (q *Queries) GetKnowledgeBaseIngestionItemContentByRef(ctx context.Context, arg GetKnowledgeBaseIngestionItemContentByRefParams) (KnowledgeBaseIngestionItemContent, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeBaseIngestionItemContentByRef,
		arg.OrganizationCode,
		arg.Provider,
		arg.SourceCode,
		arg.ItemRef,
	)
	var i KnowledgeBaseIngestionItemContent
	err := row.Scan(
		&i.ItemID,
		&i.OrganizationCode,
		&i.Provider,
		&i.SourceCode,
		&i.ItemRef,
		&i.CleanHash,
		&i.Content,
		&i.ContentFormat,
		&i.ContentCharset,
		&i.ContentSize,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKnowledgeBaseIngestionSourceByCode = `-- name: GetKnowledgeBaseIngestionSourceByCode :one
SELECT id, organization_code, provider, source_code, name, enabled, credential_ref, config, sync_cursor, last_sync_status, last_sync_error, last_synced_at, created_uid, updated_uid, created_at, updated_at
FROM knowledge_base_ingestion_sources
WHERE organization_code = ?
  AND provider = ?
  AND source_code = ?
LIMIT 1
`

type GetKnowledgeBaseIngestionSourceByCodeParams struct {
	OrganizationCode string `json:"organization_code"`
	Provider         string `json:"provider"`
	SourceCode       string `json:"source_code"`
}

func (q *Queries) GetKnowledgeBaseIngestionSourceByCode(ctx context.Context, arg GetKnowledgeBaseIngestionSourceByCodeParams) (KnowledgeBaseIngestionSource, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeBaseIngestionSourceByCode, arg.OrganizationCode, arg.Provider, arg.SourceCode)
	var i KnowledgeBaseIngestionSource
	err := row.Scan(
		&i.ID,
		&i.OrganizationCode,
		&i.Provider,
		&i.SourceCode,
		&i.Name,
		&i.Enabled,
		&i.CredentialRef,
		&i.Config,
		&i.SyncCursor,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.LastSyncedAt,
		&i.CreatedUid,
		&i.UpdatedUid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertKnowledgeBaseIngestionRun = `-- name: InsertKnowledgeBaseIngestionRun :execresult
INSERT INTO knowledge_base_ingestion_runs (
    organization_code, provider, source_code, run_type, status,
    pulled_count, changed_count, cleaned_count, skipped_count, failed_count,
    error_summary, started_at, finished_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertKnowledgeBaseIngestionRunParams struct {
	OrganizationCode string       `json:"organization_code"`
	Provider         string       `json:"provider"`
	SourceCode       string       `json:"source_code"`
	RunType          string       `json:"run_type"`
	Status           string       `json:"status"`
	PulledCount      uint32       `json:"pulled_count"`
	ChangedCount     uint32       `json:"changed_count"`
	CleanedCount     uint32       `json:"cleaned_count"`
	SkippedCount     uint32       `json:"skipped_count"`
	FailedCount      uint32       `json:"failed_count"`
	ErrorSummary     string       `json:"error_summary"`
	StartedAt        time.Time    `json:"started_at"`
	FinishedAt       sql.NullTime `json:"finished_at"`
}

func (q *Queries) InsertKnowledgeBaseIngestionRun(ctx context.Context, arg InsertKnowledgeBaseIngestionRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertKnowledgeBaseIngestionRun,
		arg.OrganizationCode,
		arg.Provider,
		arg.SourceCode,
		arg.RunType,
		arg.Status,
		arg.PulledCount,
		arg.ChangedCount,
		arg.CleanedCount,
		arg.SkippedCount,
		arg.FailedCount,
		arg.ErrorSummary,
		arg.StartedAt,
		arg.FinishedAt,
	)
}

const listEnabledKnowledgeBaseIngestionSources = `-- name: ListEnabledKnowledgeBaseIngestionSources :many
SELECT id, organization_code, provider, source_code, name, enabled, credential_ref, config, sync_cursor, last_sync_status, last_sync_error, last_synced_at, created_uid, updated_uid, created_at, updated_at
FROM knowledge_base_ingestion_sources
WHERE organization_code = ?
  AND provider = ?
  AND enabled = TRUE
ORDER BY id ASC
LIMIT ?
OFFSET ?
`

type ListEnabledKnowledgeBaseIngestionSourcesParams struct {
	OrganizationCode string `json:"organization_code"`
	Provider         string `json:"provider"`
	Limit            int32  `json:"limit"`
	Offset           int32  `json:"offset"`
}

func (q *Queries) ListEnabledKnowledgeBaseIngestionSources(ctx context.Context, arg ListEnabledKnowledgeBaseIngestionSourcesParams) ([]KnowledgeBaseIngestionSource, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledKnowledgeBaseIngestionSources,
		arg.OrganizationCode,
		arg.Provider,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeBaseIngestionSource{}
	for rows.Next() {
		var i KnowledgeBaseIngestionSource
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationCode,
			&i.Provider,
			&i.SourceCode,
			&i.Name,
			&i.Enabled,
			&i.CredentialRef,
			&i.Config,
			&i.SyncCursor,
			&i.LastSyncStatus,
			&i.LastSyncError,
			&i.LastSyncedAt,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeBaseIngestionItemsByRefs = `-- name: ListKnowledgeBaseIngestionItemsByRefs :many
SELECT id, organization_code, provider, source_code, item_ref, item_type, title, source_url, extension, raw_hash, clean_hash, clean_size, cleaner_version, status, snapshot_meta, last_error, last_pulled_at, last_cleaned_at, created_at, updated_at
FROM knowledge_base_ingestion_items
WHERE organization_code = ?
  AND provider = ?
  AND source_code = ?
  AND item_ref IN (/*SLICE:item_refs*/?)
ORDER BY id ASC
`

type ListKnowledgeBaseIngestionItemsByRefsParams struct {
	OrganizationCode string   `json:"organization_code"`
	Provider         string   `json:"provider"`
	SourceCode       string   `json:"source_code"`
	ItemRefs         []string `json:"item_refs"`
}

func (q *Queries) ListKnowledgeBaseIngestionItemsByRefs(ctx context.Context, arg ListKnowledgeBaseIngestionItemsByRefsParams) ([]KnowledgeBaseIngestionItem, error) {
	query := listKnowledgeBaseIngestionItemsByRefs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrganizationCode)
	queryParams = append(queryParams, arg.Provider)
	queryParams = append(queryParams, arg.SourceCode)
	if len(arg.ItemRefs) > 0 {
		for _, v := range arg.ItemRefs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:item_refs*/?", strings.Repeat(",?", len(arg.ItemRefs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:item_refs*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeBaseIngestionItem{}
	for rows.Next() {
		var i KnowledgeBaseIngestionItem
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationCode,
			&i.Provider,
			&i.SourceCode,
			&i.ItemRef,
			&i.ItemType,
			&i.Title,
			&i.SourceUrl,
			&i.Extension,
			&i.RawHash,
			&i.CleanHash,
			&i.CleanSize,
			&i.CleanerVersion,
			&i.Status,
			&i.SnapshotMeta,
			&i.LastError,
			&i.LastPulledAt,
			&i.LastCleanedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeBaseIngestionItemsBySourceAndStatus = `-- name: ListKnowledgeBaseIngestionItemsBySourceAndStatus :many
SELECT id, organization_code, provider, source_code, item_ref, item_type, title, source_url, extension, raw_hash, clean_hash, clean_size, cleaner_version, status, snapshot_meta, last_error, last_pulled_at, last_cleaned_at, created_at, updated_at
FROM knowledge_base_ingestion_items
WHERE organization_code = ?
  AND provider = ?
  AND source_code = ?
  AND status IN (/*SLICE:statuses*/?)
  AND id > ?
ORDER BY id ASC
LIMIT ?
OFFSET ?
`

type ListKnowledgeBaseIngestionItemsBySourceAndStatusParams struct {
	OrganizationCode string   `json:"organization_code"`
	Provider         string   `json:"provider"`
	SourceCode       string   `json:"source_code"`
	Statuses         []string `json:"statuses"`
	AfterID          int64    `json:"after_id"`
	Limit            int32    `json:"limit"`
	Offset           int32    `json:"offset"`
}

func (q *Queries) ListKnowledgeBaseIngestionItemsBySourceAndStatus(ctx context.Context, arg ListKnowledgeBaseIngestionItemsBySourceAndStatusParams) ([]KnowledgeBaseIngestionItem, error) {
	query := listKnowledgeBaseIngestionItemsBySourceAndStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrganizationCode)
	queryParams = append(queryParams, arg.Provider)
	queryParams = append(queryParams, arg.SourceCode)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.AfterID)
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeBaseIngestionItem{}
	for rows.Next() {
		var i KnowledgeBaseIngestionItem
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationCode,
			&i.Provider,
			&i.SourceCode,
			&i.ItemRef,
			&i.ItemType,
			&i.Title,
			&i.SourceUrl,
			&i.Extension,
			&i.RawHash,
			&i.CleanHash,
			&i.CleanSize,
			&i.CleanerVersion,
			&i.Status,
			&i.SnapshotMeta,
			&i.LastError,
			&i.LastPulledAt,
			&i.LastCleanedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markKnowledgeBaseIngestionItemFailed = `-- name: MarkKnowledgeBaseIngestionItemFailed :execrows
UPDATE knowledge_base_ingestion_items
SET status = 'failed',
    last_error = ?,
    updated_at = ?
WHERE organization_code = ?
  AND provider = ?
  AND source_code = ?
  AND item_ref = ?
`

type MarkKnowledgeBaseIngestionItemFailedParams struct {
	LastError        string    `json:"last_error"`
	UpdatedAt        time.Time `json:"updated_at"`
	OrganizationCode string    `json:"organization_code"`
	Provider         string    `json:"provider"`
	SourceCode       string    `json:"source_code"`
	ItemRef          string    `json:"item_ref"`
}

func (q *Queries) MarkKnowledgeBaseIngestionItemFailed(ctx context.Context, arg MarkKnowledgeBaseIngestionItemFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markKnowledgeBaseIngestionItemFailed,
		arg.LastError,
		arg.UpdatedAt,
		arg.OrganizationCode,
		arg.Provider,
		arg.SourceCode,
		arg.ItemRef,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseKnowledgeBaseIngestionSourceSync = `-- name: ReleaseKnowledgeBaseIngestionSourceSync :execrows
UPDATE knowledge_base_ingestion_sources
SET last_sync_status = ?,
    last_sync_error = ?,
    updated_at = ?
WHERE organization_code = ?
  AND provider = ?
  AND source_code = ?
  AND last_sync_status = 'running'
`

type ReleaseKnowledgeBaseIngestionSourceSyncParams struct {
	LastSyncStatus   string    `json:"last_sync_status"`
	LastSyncError    string    `json:"last_sync_error"`
	UpdatedAt        time.Time `json:"updated_at"`
	OrganizationCode string    `json:"organization_code"`
	Provider         string    `json:"provider"`
	SourceCode       string    `json:"source_code"`
}

func (q *Queries) ReleaseKnowledgeBaseIngestionSourceSync(ctx context.Context, arg ReleaseKnowledgeBaseIngestionSourceSyncParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, releaseKnowledgeBaseIngestionSourceSync,
		arg.LastSyncStatus,
		arg.LastSyncError,
		arg.UpdatedAt,
		arg.OrganizationCode,
		arg.Provider,
		arg.SourceCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const tryAcquireKnowledgeBaseIngestionSourceSync = `-- name: TryAcquireKnowledgeBaseIngestionSourceSync :execrows
UPDATE knowledge_base_ingestion_sources
SET last_sync_status = 'running',
    last_sync_error = '',
    updated_at = ?
WHERE organization_code = ?
  AND provider = ?
  AND source_code = ?
  AND enabled = TRUE
  AND (
    last_sync_status <> 'running'
    OR updated_at < ?
  )
`

type TryAcquireKnowledgeBaseIngestionSourceSyncParams struct {
	UpdatedAt        time.Time `json:"updated_at"`
	OrganizationCode string    `json:"organization_code"`
	Provider         string    `json:"provider"`
	SourceCode       string    `json:"source_code"`
	StaleBefore      time.Time `json:"stale_before"`
}

func (q *Queries) TryAcquireKnowledgeBaseIngestionSourceSync(ctx context.Context, arg TryAcquireKnowledgeBaseIngestionSourceSyncParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, tryAcquireKnowledgeBaseIngestionSourceSync,
		arg.UpdatedAt,
		arg.OrganizationCode,
		arg.Provider,
		arg.SourceCode,
		arg.StaleBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateKnowledgeBaseIngestionSourceSyncStatus = `-- name: UpdateKnowledgeBaseIngestionSourceSyncStatus :execrows
UPDATE knowledge_base_ingestion_sources
SET sync_cursor = ?,
    last_sync_status = ?,
    last_sync_error = ?,
    last_synced_at = ?,
    updated_at = ?
WHERE organization_code = ?
  AND provider = ?
  AND source_code = ?
`

type UpdateKnowledgeBaseIngestionSourceSyncStatusParams struct {
	SyncCursor       []byte       `json:"sync_cursor"`
	LastSyncStatus   string       `json:"last_sync_status"`
	LastSyncError    string       `json:"last_sync_error"`
	LastSyncedAt     sql.NullTime `json:"last_synced_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	OrganizationCode string       `json:"organization_code"`
	Provider         string       `json:"provider"`
	SourceCode       string       `json:"source_code"`
}

func (q *Queries) UpdateKnowledgeBaseIngestionSourceSyncStatus(ctx context.Context, arg UpdateKnowledgeBaseIngestionSourceSyncStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateKnowledgeBaseIngestionSourceSyncStatus,
		arg.SyncCursor,
		arg.LastSyncStatus,
		arg.LastSyncError,
		arg.LastSyncedAt,
		arg.UpdatedAt,
		arg.OrganizationCode,
		arg.Provider,
		arg.SourceCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertKnowledgeBaseIngestionItem = `-- name: UpsertKnowledgeBaseIngestionItem :execresult
INSERT INTO knowledge_base_ingestion_items (
    organization_code, provider, source_code, item_ref, item_type,
    title, source_url, extension, raw_hash, clean_hash, clean_size,
    cleaner_version, status, snapshot_meta, last_error,
    last_pulled_at, last_cleaned_at, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON DUPLICATE KEY UPDATE
    item_type = VALUES(item_type),
    title = VALUES(title),
    source_url = VALUES(source_url),
    extension = VALUES(extension),
    raw_hash = VALUES(raw_hash),
    clean_hash = VALUES(clean_hash),
    clean_size = VALUES(clean_size),
    cleaner_version = VALUES(cleaner_version),
    status = VALUES(status),
    snapshot_meta = VALUES(snapshot_meta),
    last_error = VALUES(last_error),
    last_pulled_at = VALUES(last_pulled_at),
    last_cleaned_at = VALUES(last_cleaned_at),
    updated_at = VALUES(updated_at)
`

type UpsertKnowledgeBaseIngestionItemParams struct {
	OrganizationCode string       `json:"organization_code"`
	Provider         string       `json:"provider"`
	SourceCode       string       `json:"source_code"`
	ItemRef          string       `json:"item_ref"`
	ItemType         string       `json:"item_type"`
	Title            string       `json:"title"`
	SourceUrl        string       `json:"source_url"`
	Extension        string       `json:"extension"`
	RawHash          string       `json:"raw_hash"`
	CleanHash        string       `json:"clean_hash"`
	CleanSize        uint64       `json:"clean_size"`
	CleanerVersion   string       `json:"cleaner_version"`
	Status           string       `json:"status"`
	SnapshotMeta     []byte       `json:"snapshot_meta"`
	LastError        string       `json:"last_error"`
	LastPulledAt     sql.NullTime `json:"last_pulled_at"`
	LastCleanedAt    sql.NullTime `json:"last_cleaned_at"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
}

func (q *Queries) UpsertKnowledgeBaseIngestionItem(ctx context.Context, arg UpsertKnowledgeBaseIngestionItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertKnowledgeBaseIngestionItem,
		arg.OrganizationCode,
		arg.Provider,
		arg.SourceCode,
		arg.ItemRef,
		arg.ItemType,
		arg.Title,
		arg.SourceUrl,
		arg.Extension,
		arg.RawHash,
		arg.CleanHash,
		arg.CleanSize,
		arg.CleanerVersion,
		arg.Status,
		arg.SnapshotMeta,
		arg.LastError,
		arg.LastPulledAt,
		arg.LastCleanedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const upsertKnowledgeBaseIngestionItemContent = `-- name: UpsertKnowledgeBaseIngestionItemContent :execresult
INSERT INTO knowledge_base_ingestion_item_contents (
    item_id, organization_code, provider, source_code, item_ref,
    clean_hash, content, content_format, content_charset, content_size,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON DUPLICATE KEY UPDATE
    organization_code = VALUES(organization_code),
    provider = VALUES(provider),
    source_code = VALUES(source_code),
    item_ref = VALUES(item_ref),
    clean_hash = VALUES(clean_hash),
    content = VALUES(content),
    content_format = VALUES(content_format),
    content_charset = VALUES(content_charset),
    content_size = VALUES(content_size),
    updated_at = VALUES(updated_at)
`

type UpsertKnowledgeBaseIngestionItemContentParams struct {
	ItemID           int64     `json:"item_id"`
	OrganizationCode string    `json:"organization_code"`
	Provider         string    `json:"provider"`
	SourceCode       string    `json:"source_code"`
	ItemRef          string    `json:"item_ref"`
	CleanHash        string    `json:"clean_hash"`
	Content          string    `json:"content"`
	ContentFormat    string    `json:"content_format"`
	ContentCharset   string    `json:"content_charset"`
	ContentSize      uint64    `json:"content_size"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) UpsertKnowledgeBaseIngestionItemContent(ctx context.Context, arg UpsertKnowledgeBaseIngestionItemContentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertKnowledgeBaseIngestionItemContent,
		arg.ItemID,
		arg.OrganizationCode,
		arg.Provider,
		arg.SourceCode,
		arg.ItemRef,
		arg.CleanHash,
		arg.Content,
		arg.ContentFormat,
		arg.ContentCharset,
		arg.ContentSize,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const upsertKnowledgeBaseIngestionSource = `-- name: UpsertKnowledgeBaseIngestionSource :execresult
INSERT INTO knowledge_base_ingestion_sources (
    organization_code, provider, source_code, name, enabled, credential_ref,
    config, sync_cursor, last_sync_status, last_sync_error, last_synced_at,
    created_uid, updated_uid, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    enabled = VALUES(enabled),
    credential_ref = VALUES(credential_ref),
    config = VALUES(config),
    sync_cursor = VALUES(sync_cursor),
    last_sync_status = VALUES(last_sync_status),
    last_sync_error = VALUES(last_sync_error),
    last_synced_at = VALUES(last_synced_at),
    updated_uid = VALUES(updated_uid),
    updated_at = VALUES(updated_at)
`

type UpsertKnowledgeBaseIngestionSourceParams struct {
	OrganizationCode string       `json:"organization_code"`
	Provider         string       `json:"provider"`
	SourceCode       string       `json:"source_code"`
	Name             string       `json:"name"`
	Enabled          bool         `json:"enabled"`
	CredentialRef    string       `json:"credential_ref"`
	Config           []byte       `json:"config"`
	SyncCursor       []byte       `json:"sync_cursor"`
	LastSyncStatus   string       `json:"last_sync_status"`
	LastSyncError    string       `json:"last_sync_error"`
	LastSyncedAt     sql.NullTime `json:"last_synced_at"`
	CreatedUid       string       `json:"created_uid"`
	UpdatedUid       string       `json:"updated_uid"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
}

func (q *Queries) UpsertKnowledgeBaseIngestionSource(ctx context.Context, arg UpsertKnowledgeBaseIngestionSourceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertKnowledgeBaseIngestionSource,
		arg.OrganizationCode,
		arg.Provider,
		arg.SourceCode,
		arg.Name,
		arg.Enabled,
		arg.CredentialRef,
		arg.Config,
		arg.SyncCursor,
		arg.LastSyncStatus,
		arg.LastSyncError,
		arg.LastSyncedAt,
		arg.CreatedUid,
		arg.UpdatedUid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}
