// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: knowledge_base_binding.sql

package mysqlsqlc

import (
	"context"
	"strings"
	"time"
)

const deleteKnowledgeBaseBindingsByCode = `-- name: DeleteKnowledgeBaseBindingsByCode :execrows
DELETE FROM knowledge_base_bindings
WHERE knowledge_base_code = ?
`

func (q *Queries) DeleteKnowledgeBaseBindingsByCode(ctx context.Context, knowledgeBaseCode string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteKnowledgeBaseBindingsByCode, knowledgeBaseCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteKnowledgeBaseBindingsByCodeAndType = `-- name: DeleteKnowledgeBaseBindingsByCodeAndType :execrows
DELETE FROM knowledge_base_bindings
WHERE knowledge_base_code = ?
  AND bind_type = ?
`

type DeleteKnowledgeBaseBindingsByCodeAndTypeParams struct {
	KnowledgeBaseCode string `json:"knowledge_base_code"`
	BindType          string `json:"bind_type"`
}

func (q *Queries) DeleteKnowledgeBaseBindingsByCodeAndType(ctx context.Context, arg DeleteKnowledgeBaseBindingsByCodeAndTypeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteKnowledgeBaseBindingsByCodeAndType, arg.KnowledgeBaseCode, arg.BindType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertKnowledgeBaseBinding = `-- name: InsertKnowledgeBaseBinding :exec
INSERT INTO knowledge_base_bindings
    (knowledge_base_code, bind_type, bind_id, organization_code, created_uid, updated_uid, created_at, updated_at)
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertKnowledgeBaseBindingParams struct {
	KnowledgeBaseCode string    `json:"knowledge_base_code"`
	BindType          string    `json:"bind_type"`
	BindID            string    `json:"bind_id"`
	OrganizationCode  string    `json:"organization_code"`
	CreatedUid        string    `json:"created_uid"`
	UpdatedUid        string    `json:"updated_uid"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (q *Queries) InsertKnowledgeBaseBinding(ctx context.Context, arg InsertKnowledgeBaseBindingParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeBaseBinding,
		arg.KnowledgeBaseCode,
		arg.BindType,
		arg.BindID,
		arg.OrganizationCode,
		arg.CreatedUid,
		arg.UpdatedUid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listKnowledgeBaseBindingIDs = `-- name: ListKnowledgeBaseBindingIDs :many
SELECT bind_id
FROM knowledge_base_bindings
WHERE knowledge_base_code = ?
  AND bind_type = ?
ORDER BY id ASC
`

type ListKnowledgeBaseBindingIDsParams struct {
	KnowledgeBaseCode string `json:"knowledge_base_code"`
	BindType          string `json:"bind_type"`
}

func (q *Queries) ListKnowledgeBaseBindingIDs(ctx context.Context, arg ListKnowledgeBaseBindingIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeBaseBindingIDs, arg.KnowledgeBaseCode, arg.BindType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var bind_id string
		if err := rows.Scan(&bind_id); err != nil {
			return nil, err
		}
		items = append(items, bind_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeBaseBindingPairsByCodes = `-- name: ListKnowledgeBaseBindingPairsByCodes :many
SELECT knowledge_base_code, bind_id
FROM knowledge_base_bindings
WHERE bind_type = ?
  AND knowledge_base_code IN (/*SLICE:knowledge_base_codes*/?)
ORDER BY id ASC
`

type ListKnowledgeBaseBindingPairsByCodesParams struct {
	BindType           string   `json:"bind_type"`
	KnowledgeBaseCodes []string `json:"knowledge_base_codes"`
}

type ListKnowledgeBaseBindingPairsByCodesRow struct {
	KnowledgeBaseCode string `json:"knowledge_base_code"`
	BindID            string `json:"bind_id"`
}

func (q *Queries) ListKnowledgeBaseBindingPairsByCodes(ctx context.Context, arg ListKnowledgeBaseBindingPairsByCodesParams) ([]ListKnowledgeBaseBindingPairsByCodesRow, error) {
	query := listKnowledgeBaseBindingPairsByCodes
	var queryParams []interface{}
	queryParams = append(queryParams, arg.BindType)
	if len(arg.KnowledgeBaseCodes) > 0 {
		for _, v := range arg.KnowledgeBaseCodes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:knowledge_base_codes*/?", strings.Repeat(",?", len(arg.KnowledgeBaseCodes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:knowledge_base_codes*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKnowledgeBaseBindingPairsByCodesRow{}
	for rows.Next() {
		var i ListKnowledgeBaseBindingPairsByCodesRow
		if err := rows.Scan(&i.KnowledgeBaseCode, &i.BindID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeBaseCodesByBindID = `-- name: ListKnowledgeBaseCodesByBindID :many
SELECT knowledge_base_code
FROM knowledge_base_bindings
WHERE bind_type = ?
  AND bind_id = ?
  AND organization_code = ?
ORDER BY id ASC
`

type ListKnowledgeBaseCodesByBindIDParams struct {
	BindType         string `json:"bind_type"`
	BindID           string `json:"bind_id"`
	OrganizationCode string `json:"organization_code"`
}

func (q *Queries) ListKnowledgeBaseCodesByBindID(ctx context.Context, arg ListKnowledgeBaseCodesByBindIDParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeBaseCodesByBindID, arg.BindType, arg.BindID, arg.OrganizationCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var knowledge_base_code string
		if err := rows.Scan(&knowledge_base_code); err != nil {
			return nil, err
		}
		items = append(items, knowledge_base_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
