// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: source_binding.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const deleteSourceBindingItemsByBinding = `-- name: DeleteSourceBindingItemsByBinding :execrows
DELETE FROM knowledge_source_binding_items
WHERE binding_id = ?
`

func (q *Queries) DeleteSourceBindingItemsByBinding(ctx context.Context, bindingID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSourceBindingItemsByBinding, bindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSourceBindingItemsByKnowledgeBase = `-- name: DeleteSourceBindingItemsByKnowledgeBase :execrows
DELETE FROM knowledge_source_binding_items
WHERE binding_id IN (
    SELECT id FROM knowledge_source_bindings WHERE knowledge_base_code = ?
)
`

func (q *Queries) DeleteSourceBindingItemsByKnowledgeBase(ctx context.Context, knowledgeBaseCode string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSourceBindingItemsByKnowledgeBase, knowledgeBaseCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSourceBindingTargetsByKnowledgeBase = `-- name: DeleteSourceBindingTargetsByKnowledgeBase :execrows
DELETE t
FROM knowledge_source_bindings b
STRAIGHT_JOIN knowledge_source_binding_targets t ON t.binding_id = b.id
WHERE b.knowledge_base_code = ?
`

func (q *Queries) DeleteSourceBindingTargetsByKnowledgeBase(ctx context.Context, knowledgeBaseCode string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSourceBindingTargetsByKnowledgeBase, knowledgeBaseCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSourceBindingsByKnowledgeBase = `-- name: DeleteSourceBindingsByKnowledgeBase :execrows
DELETE FROM knowledge_source_bindings
WHERE knowledge_base_code = ?
`

func (q *Queries) DeleteSourceBindingsByKnowledgeBase(ctx context.Context, knowledgeBaseCode string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSourceBindingsByKnowledgeBase, knowledgeBaseCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertKnowledgeSourceBinding = `-- name: InsertKnowledgeSourceBinding :execresult
INSERT INTO knowledge_source_bindings (
    organization_code, knowledge_base_code, provider, root_type, root_ref, sync_mode, sync_config,
    enabled, created_uid, updated_uid, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertKnowledgeSourceBindingParams struct {
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	Provider          string          `json:"provider"`
	RootType          string          `json:"root_type"`
	RootRef           string          `json:"root_ref"`
	SyncMode          string          `json:"sync_mode"`
	SyncConfig        json.RawMessage `json:"sync_config"`
	Enabled           bool            `json:"enabled"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

func (q *Queries) InsertKnowledgeSourceBinding(ctx context.Context, arg InsertKnowledgeSourceBindingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertKnowledgeSourceBinding,
		arg.OrganizationCode,
		arg.KnowledgeBaseCode,
		arg.Provider,
		arg.RootType,
		arg.RootRef,
		arg.SyncMode,
		arg.SyncConfig,
		arg.Enabled,
		arg.CreatedUid,
		arg.UpdatedUid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const insertKnowledgeSourceBindingItem = `-- name: InsertKnowledgeSourceBindingItem :exec
INSERT INTO knowledge_source_binding_items (
    binding_id, source_item_id, resolve_reason, last_resolved_at, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type InsertKnowledgeSourceBindingItemParams struct {
	BindingID      int64        `json:"binding_id"`
	SourceItemID   int64        `json:"source_item_id"`
	ResolveReason  string       `json:"resolve_reason"`
	LastResolvedAt sql.NullTime `json:"last_resolved_at"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

func (q *Queries) InsertKnowledgeSourceBindingItem(ctx context.Context, arg InsertKnowledgeSourceBindingItemParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeSourceBindingItem,
		arg.BindingID,
		arg.SourceItemID,
		arg.ResolveReason,
		arg.LastResolvedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertKnowledgeSourceBindingTarget = `-- name: InsertKnowledgeSourceBindingTarget :exec
INSERT INTO knowledge_source_binding_targets (
    binding_id, target_type, target_ref, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?
)
`

type InsertKnowledgeSourceBindingTargetParams struct {
	BindingID  int64     `json:"binding_id"`
	TargetType string    `json:"target_type"`
	TargetRef  string    `json:"target_ref"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) InsertKnowledgeSourceBindingTarget(ctx context.Context, arg InsertKnowledgeSourceBindingTargetParams) error {
	_, err := q.db.ExecContext(ctx, insertKnowledgeSourceBindingTarget,
		arg.BindingID,
		arg.TargetType,
		arg.TargetRef,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listKnowledgeSourceBindingItemsByKnowledgeBase = `-- name: ListKnowledgeSourceBindingItemsByKnowledgeBase :many
SELECT
    bi.id, bi.binding_id, bi.source_item_id, bi.resolve_reason, bi.last_resolved_at, bi.created_at, bi.updated_at
FROM knowledge_source_binding_items bi
INNER JOIN knowledge_source_bindings b ON b.id = bi.binding_id
WHERE b.knowledge_base_code = ?
ORDER BY bi.id ASC
`

func (q *Queries) ListKnowledgeSourceBindingItemsByKnowledgeBase(ctx context.Context, knowledgeBaseCode string) ([]KnowledgeSourceBindingItem, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeSourceBindingItemsByKnowledgeBase, knowledgeBaseCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeSourceBindingItem{}
	for rows.Next() {
		var i KnowledgeSourceBindingItem
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.SourceItemID,
			&i.ResolveReason,
			&i.LastResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeSourceBindingsByKnowledgeBase = `-- name: ListKnowledgeSourceBindingsByKnowledgeBase :many
SELECT
    b.id, b.organization_code, b.knowledge_base_code, b.provider, b.root_type, b.root_ref, b.sync_mode,
    COALESCE(b.sync_config, CAST('null' AS JSON)) AS sync_config, b.enabled, b.created_uid, b.updated_uid,
    b.created_at, b.updated_at,
    t.id, COALESCE(t.target_type, ''), COALESCE(t.target_ref, ''), t.created_at, t.updated_at
FROM knowledge_source_bindings b
LEFT JOIN knowledge_source_binding_targets t FORCE INDEX (uk_kb_source_binding_targets) ON t.binding_id = b.id
WHERE b.knowledge_base_code = ?
ORDER BY b.id ASC, t.id ASC
`

type ListKnowledgeSourceBindingsByKnowledgeBaseRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	Provider          string          `json:"provider"`
	RootType          string          `json:"root_type"`
	RootRef           string          `json:"root_ref"`
	SyncMode          string          `json:"sync_mode"`
	SyncConfig        json.RawMessage `json:"sync_config"`
	Enabled           bool            `json:"enabled"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	ID_2              sql.NullInt64   `json:"id_2"`
	TargetType        string          `json:"target_type"`
	TargetRef         string          `json:"target_ref"`
	CreatedAt_2       sql.NullTime    `json:"created_at_2"`
	UpdatedAt_2       sql.NullTime    `json:"updated_at_2"`
}

func (q *Queries) ListKnowledgeSourceBindingsByKnowledgeBase(ctx context.Context, knowledgeBaseCode string) ([]ListKnowledgeSourceBindingsByKnowledgeBaseRow, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeSourceBindingsByKnowledgeBase, knowledgeBaseCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKnowledgeSourceBindingsByKnowledgeBaseRow{}
	for rows.Next() {
		var i ListKnowledgeSourceBindingsByKnowledgeBaseRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationCode,
			&i.KnowledgeBaseCode,
			&i.Provider,
			&i.RootType,
			&i.RootRef,
			&i.SyncMode,
			&i.SyncConfig,
			&i.Enabled,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.TargetType,
			&i.TargetRef,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRealtimeProjectSourceBindingsByProject = `-- name: ListRealtimeProjectSourceBindingsByProject :many
SELECT
    b.id, b.organization_code, b.knowledge_base_code, b.provider, b.root_type, b.root_ref, b.sync_mode,
    COALESCE(b.sync_config, CAST('null' AS JSON)) AS sync_config, b.enabled, b.created_uid, b.updated_uid,
    b.created_at, b.updated_at,
    t.id, COALESCE(t.target_type, ''), COALESCE(t.target_ref, ''), t.created_at, t.updated_at
FROM knowledge_source_bindings b
LEFT JOIN knowledge_source_binding_targets t FORCE INDEX (uk_kb_source_binding_targets) ON t.binding_id = b.id
WHERE b.organization_code = ?
  AND b.provider = 'project'
  AND b.root_type = 'project'
  AND b.root_ref = ?
  AND b.sync_mode = 'realtime'
ORDER BY b.id ASC, t.id ASC
`

type ListRealtimeProjectSourceBindingsByProjectParams struct {
	OrganizationCode string `json:"organization_code"`
	RootRef          string `json:"root_ref"`
}

type ListRealtimeProjectSourceBindingsByProjectRow struct {
	ID                int64           `json:"id"`
	OrganizationCode  string          `json:"organization_code"`
	KnowledgeBaseCode string          `json:"knowledge_base_code"`
	Provider          string          `json:"provider"`
	RootType          string          `json:"root_type"`
	RootRef           string          `json:"root_ref"`
	SyncMode          string          `json:"sync_mode"`
	SyncConfig        json.RawMessage `json:"sync_config"`
	Enabled           bool            `json:"enabled"`
	CreatedUid        string          `json:"created_uid"`
	UpdatedUid        string          `json:"updated_uid"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	ID_2              sql.NullInt64   `json:"id_2"`
	TargetType        string          `json:"target_type"`
	TargetRef         string          `json:"target_ref"`
	CreatedAt_2       sql.NullTime    `json:"created_at_2"`
	UpdatedAt_2       sql.NullTime    `json:"updated_at_2"`
}

func (q *Queries) ListRealtimeProjectSourceBindingsByProject(ctx context.Context, arg ListRealtimeProjectSourceBindingsByProjectParams) ([]ListRealtimeProjectSourceBindingsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listRealtimeProjectSourceBindingsByProject, arg.OrganizationCode, arg.RootRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRealtimeProjectSourceBindingsByProjectRow{}
	for rows.Next() {
		var i ListRealtimeProjectSourceBindingsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationCode,
			&i.KnowledgeBaseCode,
			&i.Provider,
			&i.RootType,
			&i.RootRef,
			&i.SyncMode,
			&i.SyncConfig,
			&i.Enabled,
			&i.CreatedUid,
			&i.UpdatedUid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.TargetType,
			&i.TargetRef,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertKnowledgeSourceItem = `-- name: UpsertKnowledgeSourceItem :execresult
INSERT INTO knowledge_source_items (
    organization_code, provider, root_type, root_ref, group_ref, item_type, item_ref,
    display_name, extension, content_hash, snapshot_meta, last_resolved_at, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON DUPLICATE KEY UPDATE
    root_type = VALUES(root_type),
    root_ref = VALUES(root_ref),
    group_ref = VALUES(group_ref),
    item_type = VALUES(item_type),
    display_name = VALUES(display_name),
    extension = VALUES(extension),
    content_hash = VALUES(content_hash),
    snapshot_meta = VALUES(snapshot_meta),
    last_resolved_at = VALUES(last_resolved_at),
    updated_at = VALUES(updated_at),
    id = LAST_INSERT_ID(id)
`

type UpsertKnowledgeSourceItemParams struct {
	OrganizationCode string          `json:"organization_code"`
	Provider         string          `json:"provider"`
	RootType         string          `json:"root_type"`
	RootRef          string          `json:"root_ref"`
	GroupRef         string          `json:"group_ref"`
	ItemType         string          `json:"item_type"`
	ItemRef          string          `json:"item_ref"`
	DisplayName      string          `json:"display_name"`
	Extension        string          `json:"extension"`
	ContentHash      string          `json:"content_hash"`
	SnapshotMeta     json.RawMessage `json:"snapshot_meta"`
	LastResolvedAt   sql.NullTime    `json:"last_resolved_at"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

func (q *Queries) UpsertKnowledgeSourceItem(ctx context.Context, arg UpsertKnowledgeSourceItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertKnowledgeSourceItem,
		arg.OrganizationCode,
		arg.Provider,
		arg.RootType,
		arg.RootRef,
		arg.GroupRef,
		arg.ItemType,
		arg.ItemRef,
		arg.DisplayName,
		arg.Extension,
		arg.ContentHash,
		arg.SnapshotMeta,
		arg.LastResolvedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}
