// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: super_magic_agent.sql

package mysqlsqlc

import (
	"context"
	"strings"
)

const listExistingSuperMagicAgentCodesByOrg = `-- name: ListExistingSuperMagicAgentCodesByOrg :many
SELECT code
FROM magic_super_magic_agents
WHERE organization_code = ?
  AND deleted_at IS NULL
  AND code IN (/*SLICE:codes*/?)
`

type ListExistingSuperMagicAgentCodesByOrgParams struct {
	OrganizationCode string   `json:"organization_code"`
	Codes            []string `json:"codes"`
}

func (q *Queries) ListExistingSuperMagicAgentCodesByOrg(ctx context.Context, arg ListExistingSuperMagicAgentCodesByOrgParams) ([]string, error) {
	query := listExistingSuperMagicAgentCodesByOrg
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrganizationCode)
	if len(arg.Codes) > 0 {
		for _, v := range arg.Codes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:codes*/?", strings.Repeat(",?", len(arg.Codes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:codes*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
