// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: super_magic_project.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
	"strings"
)

const listSuperMagicProjectMembersByProjectIDs = `-- name: ListSuperMagicProjectMembersByProjectIDs :many
SELECT project_id, organization_code, status, role, deleted_at
FROM magic_super_agent_project_members
WHERE project_id IN (/*SLICE:project_ids*/?)
`

type ListSuperMagicProjectMembersByProjectIDsRow struct {
	ProjectID        int64        `json:"project_id"`
	OrganizationCode string       `json:"organization_code"`
	Status           int8         `json:"status"`
	Role             string       `json:"role"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
}

func (q *Queries) ListSuperMagicProjectMembersByProjectIDs(ctx context.Context, projectIds []int64) ([]ListSuperMagicProjectMembersByProjectIDsRow, error) {
	query := listSuperMagicProjectMembersByProjectIDs
	var queryParams []interface{}
	if len(projectIds) > 0 {
		for _, v := range projectIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:project_ids*/?", strings.Repeat(",?", len(projectIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:project_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuperMagicProjectMembersByProjectIDsRow{}
	for rows.Next() {
		var i ListSuperMagicProjectMembersByProjectIDsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.OrganizationCode,
			&i.Status,
			&i.Role,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuperMagicProjectWorkspaceMappings = `-- name: ListSuperMagicProjectWorkspaceMappings :many
SELECT id, workspace_id
FROM magic_super_agent_project
WHERE user_organization_code = ?
  AND id IN (/*SLICE:project_ids*/?)
  AND deleted_at IS NULL
`

type ListSuperMagicProjectWorkspaceMappingsParams struct {
	UserOrganizationCode string  `json:"user_organization_code"`
	ProjectIds           []int64 `json:"project_ids"`
}

type ListSuperMagicProjectWorkspaceMappingsRow struct {
	ID          int64         `json:"id"`
	WorkspaceID sql.NullInt64 `json:"workspace_id"`
}

func (q *Queries) ListSuperMagicProjectWorkspaceMappings(ctx context.Context, arg ListSuperMagicProjectWorkspaceMappingsParams) ([]ListSuperMagicProjectWorkspaceMappingsRow, error) {
	query := listSuperMagicProjectWorkspaceMappings
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserOrganizationCode)
	if len(arg.ProjectIds) > 0 {
		for _, v := range arg.ProjectIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:project_ids*/?", strings.Repeat(",?", len(arg.ProjectIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:project_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuperMagicProjectWorkspaceMappingsRow{}
	for rows.Next() {
		var i ListSuperMagicProjectWorkspaceMappingsRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuperMagicSharedProjectCandidates = `-- name: ListSuperMagicSharedProjectCandidates :many
SELECT id, workspace_id, is_collaboration_enabled
FROM magic_super_agent_project
WHERE user_organization_code = ?
  AND id IN (/*SLICE:project_ids*/?)
  AND deleted_at IS NULL
`

type ListSuperMagicSharedProjectCandidatesParams struct {
	UserOrganizationCode string  `json:"user_organization_code"`
	ProjectIds           []int64 `json:"project_ids"`
}

type ListSuperMagicSharedProjectCandidatesRow struct {
	ID                     int64         `json:"id"`
	WorkspaceID            sql.NullInt64 `json:"workspace_id"`
	IsCollaborationEnabled int8          `json:"is_collaboration_enabled"`
}

func (q *Queries) ListSuperMagicSharedProjectCandidates(ctx context.Context, arg ListSuperMagicSharedProjectCandidatesParams) ([]ListSuperMagicSharedProjectCandidatesRow, error) {
	query := listSuperMagicSharedProjectCandidates
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserOrganizationCode)
	if len(arg.ProjectIds) > 0 {
		for _, v := range arg.ProjectIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:project_ids*/?", strings.Repeat(",?", len(arg.ProjectIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:project_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuperMagicSharedProjectCandidatesRow{}
	for rows.Next() {
		var i ListSuperMagicSharedProjectCandidatesRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID, &i.IsCollaborationEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuperMagicWorkspacesByIDs = `-- name: ListSuperMagicWorkspacesByIDs :many
SELECT id, user_id
FROM magic_super_agent_workspaces
WHERE id IN (/*SLICE:workspace_ids*/?)
  AND deleted_at IS NULL
`

type ListSuperMagicWorkspacesByIDsRow struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListSuperMagicWorkspacesByIDs(ctx context.Context, workspaceIds []int64) ([]ListSuperMagicWorkspacesByIDsRow, error) {
	query := listSuperMagicWorkspacesByIDs
	var queryParams []interface{}
	if len(workspaceIds) > 0 {
		for _, v := range workspaceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:workspace_ids*/?", strings.Repeat(",?", len(workspaceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:workspace_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuperMagicWorkspacesByIDsRow{}
	for rows.Next() {
		var i ListSuperMagicWorkspacesByIDsRow
		if err := rows.Scan(&i.ID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
