// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_file.sql

package mysqlsqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const findProjectFileMetaByID = `-- name: FindProjectFileMetaByID :one
SELECT organization_code,
       project_id,
       file_id,
       COALESCE(file_key, '') AS file_key,
       file_name,
       COALESCE(file_extension, '') AS file_extension,
       COALESCE(file_size, 0) AS file_size,
       updated_at
FROM magic_super_agent_project_files
WHERE file_id = ?
LIMIT 1
`

type FindProjectFileMetaByIDRow struct {
	OrganizationCode string    `json:"organization_code"`
	ProjectID        uint64    `json:"project_id"`
	FileID           uint64    `json:"file_id"`
	FileKey          string    `json:"file_key"`
	FileName         string    `json:"file_name"`
	FileExtension    string    `json:"file_extension"`
	FileSize         uint64    `json:"file_size"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) FindProjectFileMetaByID(ctx context.Context, fileID uint64) (FindProjectFileMetaByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findProjectFileMetaByID, fileID)
	var i FindProjectFileMetaByIDRow
	err := row.Scan(
		&i.OrganizationCode,
		&i.ProjectID,
		&i.FileID,
		&i.FileKey,
		&i.FileName,
		&i.FileExtension,
		&i.FileSize,
		&i.UpdatedAt,
	)
	return i, err
}

const findTaskFileMetaByID = `-- name: FindTaskFileMetaByID :one
SELECT organization_code,
       project_id,
       file_id,
       COALESCE(file_key, '') AS file_key,
       file_name,
       COALESCE(file_extension, '') AS file_extension,
       COALESCE(file_size, 0) AS file_size,
       COALESCE(is_directory, FALSE) AS is_directory,
       COALESCE(is_hidden, FALSE) AS is_hidden,
       updated_at,
       deleted_at,
       COALESCE(parent_id, 0) AS parent_id
FROM magic_super_agent_task_files
WHERE file_id = ?
LIMIT 1
`

type FindTaskFileMetaByIDRow struct {
	OrganizationCode string       `json:"organization_code"`
	ProjectID        uint64       `json:"project_id"`
	FileID           uint64       `json:"file_id"`
	FileKey          string       `json:"file_key"`
	FileName         string       `json:"file_name"`
	FileExtension    string       `json:"file_extension"`
	FileSize         uint64       `json:"file_size"`
	IsDirectory      bool         `json:"is_directory"`
	IsHidden         bool         `json:"is_hidden"`
	UpdatedAt        time.Time    `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
	ParentID         uint64       `json:"parent_id"`
}

func (q *Queries) FindTaskFileMetaByID(ctx context.Context, fileID uint64) (FindTaskFileMetaByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findTaskFileMetaByID, fileID)
	var i FindTaskFileMetaByIDRow
	err := row.Scan(
		&i.OrganizationCode,
		&i.ProjectID,
		&i.FileID,
		&i.FileKey,
		&i.FileName,
		&i.FileExtension,
		&i.FileSize,
		&i.IsDirectory,
		&i.IsHidden,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ParentID,
	)
	return i, err
}

const findTaskFileRootDirectoryByProjectID = `-- name: FindTaskFileRootDirectoryByProjectID :one
SELECT organization_code,
       project_id,
       file_id,
       COALESCE(file_key, '') AS file_key,
       file_name,
       COALESCE(file_extension, '') AS file_extension,
       COALESCE(file_size, 0) AS file_size,
       COALESCE(is_directory, FALSE) AS is_directory,
       COALESCE(is_hidden, FALSE) AS is_hidden,
       updated_at,
       deleted_at,
       COALESCE(parent_id, 0) AS parent_id
FROM magic_super_agent_task_files
WHERE project_id = ?
  AND parent_id IS NULL
  AND is_directory = TRUE
  AND deleted_at IS NULL
ORDER BY file_id DESC
LIMIT 1
`

type FindTaskFileRootDirectoryByProjectIDRow struct {
	OrganizationCode string       `json:"organization_code"`
	ProjectID        uint64       `json:"project_id"`
	FileID           uint64       `json:"file_id"`
	FileKey          string       `json:"file_key"`
	FileName         string       `json:"file_name"`
	FileExtension    string       `json:"file_extension"`
	FileSize         uint64       `json:"file_size"`
	IsDirectory      bool         `json:"is_directory"`
	IsHidden         bool         `json:"is_hidden"`
	UpdatedAt        time.Time    `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
	ParentID         uint64       `json:"parent_id"`
}

func (q *Queries) FindTaskFileRootDirectoryByProjectID(ctx context.Context, projectID uint64) (FindTaskFileRootDirectoryByProjectIDRow, error) {
	row := q.db.QueryRowContext(ctx, findTaskFileRootDirectoryByProjectID, projectID)
	var i FindTaskFileRootDirectoryByProjectIDRow
	err := row.Scan(
		&i.OrganizationCode,
		&i.ProjectID,
		&i.FileID,
		&i.FileKey,
		&i.FileName,
		&i.FileExtension,
		&i.FileSize,
		&i.IsDirectory,
		&i.IsHidden,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ParentID,
	)
	return i, err
}

const listVisibleTaskFileChildrenByParent = `-- name: ListVisibleTaskFileChildrenByParent :many
SELECT organization_code,
       project_id,
       file_id,
       COALESCE(file_key, '') AS file_key,
       file_name,
       COALESCE(file_extension, '') AS file_extension,
       COALESCE(file_size, 0) AS file_size,
       COALESCE(is_directory, FALSE) AS is_directory,
       COALESCE(is_hidden, FALSE) AS is_hidden,
       updated_at,
       deleted_at,
       COALESCE(parent_id, 0) AS parent_id
FROM magic_super_agent_task_files
WHERE project_id = ?
  AND parent_id = ?
  AND is_hidden = FALSE
  AND deleted_at IS NULL
LIMIT ?
`

type ListVisibleTaskFileChildrenByParentParams struct {
	ProjectID uint64        `json:"project_id"`
	ParentID  sql.NullInt64 `json:"parent_id"`
	Limit     int32         `json:"limit"`
}

type ListVisibleTaskFileChildrenByParentRow struct {
	OrganizationCode string       `json:"organization_code"`
	ProjectID        uint64       `json:"project_id"`
	FileID           uint64       `json:"file_id"`
	FileKey          string       `json:"file_key"`
	FileName         string       `json:"file_name"`
	FileExtension    string       `json:"file_extension"`
	FileSize         uint64       `json:"file_size"`
	IsDirectory      bool         `json:"is_directory"`
	IsHidden         bool         `json:"is_hidden"`
	UpdatedAt        time.Time    `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
	ParentID         uint64       `json:"parent_id"`
}

func (q *Queries) ListVisibleTaskFileChildrenByParent(ctx context.Context, arg ListVisibleTaskFileChildrenByParentParams) ([]ListVisibleTaskFileChildrenByParentRow, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleTaskFileChildrenByParent, arg.ProjectID, arg.ParentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleTaskFileChildrenByParentRow{}
	for rows.Next() {
		var i ListVisibleTaskFileChildrenByParentRow
		if err := rows.Scan(
			&i.OrganizationCode,
			&i.ProjectID,
			&i.FileID,
			&i.FileKey,
			&i.FileName,
			&i.FileExtension,
			&i.FileSize,
			&i.IsDirectory,
			&i.IsHidden,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleTaskFileChildrenByParents = `-- name: ListVisibleTaskFileChildrenByParents :many
SELECT organization_code,
       project_id,
       file_id,
       COALESCE(file_key, '') AS file_key,
       file_name,
       COALESCE(file_extension, '') AS file_extension,
       COALESCE(file_size, 0) AS file_size,
       COALESCE(is_directory, FALSE) AS is_directory,
       COALESCE(is_hidden, FALSE) AS is_hidden,
       updated_at,
       deleted_at,
       COALESCE(parent_id, 0) AS parent_id
FROM magic_super_agent_task_files
WHERE project_id = ?
  AND parent_id IN (/*SLICE:parent_ids*/?)
  AND is_hidden = FALSE
  AND deleted_at IS NULL
LIMIT ?
`

type ListVisibleTaskFileChildrenByParentsParams struct {
	ProjectID uint64          `json:"project_id"`
	ParentIds []sql.NullInt64 `json:"parent_ids"`
	Limit     int32           `json:"limit"`
}

type ListVisibleTaskFileChildrenByParentsRow struct {
	OrganizationCode string       `json:"organization_code"`
	ProjectID        uint64       `json:"project_id"`
	FileID           uint64       `json:"file_id"`
	FileKey          string       `json:"file_key"`
	FileName         string       `json:"file_name"`
	FileExtension    string       `json:"file_extension"`
	FileSize         uint64       `json:"file_size"`
	IsDirectory      bool         `json:"is_directory"`
	IsHidden         bool         `json:"is_hidden"`
	UpdatedAt        time.Time    `json:"updated_at"`
	DeletedAt        sql.NullTime `json:"deleted_at"`
	ParentID         uint64       `json:"parent_id"`
}

func (q *Queries) ListVisibleTaskFileChildrenByParents(ctx context.Context, arg ListVisibleTaskFileChildrenByParentsParams) ([]ListVisibleTaskFileChildrenByParentsRow, error) {
	query := listVisibleTaskFileChildrenByParents
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProjectID)
	if len(arg.ParentIds) > 0 {
		for _, v := range arg.ParentIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:parent_ids*/?", strings.Repeat(",?", len(arg.ParentIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:parent_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleTaskFileChildrenByParentsRow{}
	for rows.Next() {
		var i ListVisibleTaskFileChildrenByParentsRow
		if err := rows.Scan(
			&i.OrganizationCode,
			&i.ProjectID,
			&i.FileID,
			&i.FileKey,
			&i.FileName,
			&i.FileExtension,
			&i.FileSize,
			&i.IsDirectory,
			&i.IsHidden,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
