import { createStyles } from "antd-style"

export const useStyles = createStyles(({ token }) => ({
	modalBody: {},
	header: {
		height: 40,
		marginBottom: 20,
	},
	title: {
		fontFamily: "PingFang SC",
		fontWeight: 600,
		fontStyle: "Semibold",
		fontSize: 16,
		lineHeight: "22px",
		letterSpacing: "0px",
	},
	description: {
		color: token.colorTextTertiary,
		fontFamily: "PingFang SC",
		fontWeight: 400,
		fontStyle: "Regular",
		fontSize: 12,
		lineHeight: "16px",
		letterSpacing: "0px",
		marginBottom: "10px",
	},
	oldProjectContainer: {
		display: "flex",
		flexDirection: "row",
		gap: 10,
	},
	sectionTitle: {
		fontSize: "14px",
		fontWeight: 500,
		color: token.colorText,
		marginBottom: "8px",
	},
	authorInfo: {
		display: "flex",
		alignItems: "center",
		gap: "8px",
		padding: "12px",
		backgroundColor: token.colorFillTertiary,
		borderRadius: "8px",
		marginBottom: "16px",
	},
	authorAvatar: {
		width: "24px",
		height: "24px",
		borderRadius: "50%",
		// backgroundColor: token.colorPrimary,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		// color: token.colorWhite,
		fontSize: "14px",
		fontWeight: 600,
	},
	authorText: {
		flex: 1,
	},
	authorName: {
		fontSize: "14px",
		fontWeight: 500,
		color: token.colorText,
	},
	projectName: {
		fontSize: "16px",
		color: token.colorText,
		marginTop: "4px",
	},
	formItem: {
		marginBottom: "16px",
	},
	label: {
		fontSize: "14px",
		fontWeight: 500,
		color: token.colorText,
		marginBottom: "4px",
		display: "block",
	},
	input: {
		width: "100%",
	},
	workspaceSelect: {},
	workspaceList: {
		padding: "10px",
		maxHeight: "200px",
		overflowY: "auto",
		borderRadius: "8px",
		backgroundColor: token.colorBgContainer,
	},
	workspaceItem: {
		padding: "8px 10px",
		gap: 12,
		borderRadius: 8,
		display: "flex",
		alignItems: "center",
		cursor: "pointer",
		border: "1px solid transparent", // 预留透明边框防止抖动
		"&:hover": {
			backgroundColor: token.colorFillTertiary,
		},
	},
	workspaceSelected: {
		backgroundColor: token.colorPrimaryBg,
		border: `1px solid ${token.colorPrimary}!important`, // 只改变边框颜色
		"&:hover": {
			backgroundColor: token.colorPrimaryBgHover,
		},
	},
	workspaceIcon: {
		width: "24px",
		height: "24px",
		borderRadius: "4px",
		color: "rgba(255, 193, 84, 1)",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		fontSize: "12px",
	},
	workspaceInfo: {
		flex: 1,
	},
	workspaceName: {
		fontSize: "14px",
		fontWeight: 500,
		color: token.colorText,
	},
	createNewWorkspace: {
		padding: "6px 10px",
		display: "flex",
		alignItems: "center",
		gap: "12px",
		cursor: "pointer",
		color: token.colorPrimary,
		fontSize: "14px",
		fontWeight: 500,
		transition: "all 0.2s",
		borderRadius: "8px",
		"&:hover": {
			backgroundColor: token.colorPrimaryBg,
		},
	},
	createNewIcon: {
		width: "24px",
		height: "24px",
		borderRadius: "4px",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		color: token.colorText,
	},
	createNewWorkspaceText: {
		color: token.colorText,
	},

	createWorkspaceInput: {
		marginTop: "8px",
	},
	searchInput: {
		borderRadius: 8,
	},
	emptyState: {
		padding: "24px",
		textAlign: "center",
		color: token.colorTextTertiary,
		fontSize: "14px",
	},
	footer: {
		display: "flex",
		justifyContent: "flex-end",
		gap: "12px",
		marginTop: "24px",
		paddingTop: "16px",
		borderTop: `1px solid ${token.colorBorder}`,
	},
	cancelButton: {
		minWidth: "80px",
	},
	confirmButton: {
		minWidth: "80px",
	},
	originalProjectInfoTitle: {
		fontWeight: 400,
		fontStyle: "Regular",
		fontSize: 14,
		lineHeight: "20px",
		color: token.colorTextBase,
	},
	originalProjectInfo: {
		display: "flex",
		flexDirection: "column",
		gap: "8px",
	},
	ProjectText: {
		height: "36px",
		fontWeight: 600,
		fontStyle: "Semibold",
		fontSize: 14,
		lineHeight: "20px",
		letterSpacing: "0px",
		backgroundColor: token.colorBgTextHover,
		border: `1px solid ${token.colorBorder}`,
		borderRadius: "8px",
		gap: "6px",
		color: token.magicColorUsages.text[0],
		display: "flex",
		alignItems: "center",
		justifyContent: "flex-start",
		padding: "6px",
	},
	newProjectContainer: {
		marginTop: "20px",
		padding: "20px",
		borderRadius: "12px",
		borderWidth: "1px",
		border: `1px solid ${token.colorBorder}`,
	},
	newProjectDescription: {
		fontWeight: 400,
		fontSize: 12,
		color: token.colorTextTertiary,
		marginBottom: "8px",
	},
	folderIcon: {
		color: token.magicColorUsages.text[2],
	},
	workspaceContainer: {
		marginTop: "20px",
		gap: "20px",
		borderRadius: "12px",
		borderWidth: "1px",
		border: `1px solid ${token.colorBorder}`,
	},
	searchContainer: {
		backgroundColor: token.colorBgTextHover,
		padding: 10,
		// borderRadius: 8,
		borderRadius: "8px 8px 0 0",
		marginBottom: "10px",
	},
}))
