// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"magic/internal/config/autoload"
	"magic/internal/di/app"
	"magic/internal/di/infra"
	"magic/internal/di/knowledge"
	"magic/internal/di/rebuild"
	"magic/internal/interfaces/http"
	"magic/internal/interfaces/http/handlers"
	"magic/internal/interfaces/rpc/jsonrpc/knowledge/service"
)

// Injectors from wire.go:

func InitializeApplication() (*httpapi.Server, func(), error) {
	config := infra.ProvideConfig()
	serverConfig := provideServerConfig(config)
	sugaredLogger := infra.ProvideLogger(config)
	sqlcClient, cleanup, err := infra.ProvideMySQLSQLCClient(config, sugaredLogger)
	if err != nil {
		return nil, nil, err
	}
	repository := infra.ProvideEmbeddingCacheRepository(sqlcClient, sugaredLogger)
	client, cleanup2, err := infra.ProvideRedisClient(config, sugaredLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	server := infra.ProvideRPCServerOverIPC(config, sugaredLogger)
	accessTokenProvider := infra.ProvideAccessTokenProvider(config, server, sugaredLogger)
	embeddingClientFactory := infra.ProvideEmbeddingClientFactory(config, server, sugaredLogger, accessTokenProvider)
	embeddingDefaultModel := app.ProvideEmbeddingDefaultModel(config)
	embeddingService := infra.ProvideEmbeddingService(config, client, embeddingClientFactory, embeddingDefaultModel, sugaredLogger)
	embeddingRepository := infra.ProvideEmbeddingRepository(embeddingService)
	domainService := knowledge.ProvideEmbeddingDomainService(repository, repository, embeddingRepository, sugaredLogger)
	redisLockManager := infra.ProvideRedisLockManager(client, config)
	singlePodJobRunner := infra.ProvideSinglePodJobRunner(redisLockManager)
	embeddingCacheCleanupService, err := app.ProvideEmbeddingCacheCleanupService(domainService, singlePodJobRunner, config, sugaredLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	knowledgeBaseFragmentRepository := infra.ProvideFragmentRepository(sqlcClient, sugaredLogger)
	qdrantClient, cleanup3, err := infra.ProvideQdrantClient(config, sugaredLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	vectorDBManagementRepository := infra.ProvideVectorDBManagementRepository(qdrantClient)
	fragmentVectorDBDataRepository := infra.ProvideFragmentVectorDBDataRepository(qdrantClient)
	baseRepository := infra.ProvideKnowledgeBaseRepository(sqlcClient, client, sugaredLogger)
	segmenterProvider := knowledge.ProvideFragmentRetrievalSegmenterProvider()
	fragmentDomainInfra := knowledge.ProvideFragmentDomainInfra(vectorDBManagementRepository, fragmentVectorDBDataRepository, baseRepository, embeddingDefaultModel, segmenterProvider, sugaredLogger)
	fragmentDomainService := knowledge.ProvideFragmentDomainService(knowledgeBaseFragmentRepository, domainService, fragmentDomainInfra)
	dimensionResolver := infra.ProvideEmbeddingDimensionResolver(config, embeddingService)
	qdrantConfig := app.ProvideQdrantConfig(config)
	baseDomainConfig := knowledge.ProvideKnowledgeBaseDomainConfig(embeddingDefaultModel, qdrantConfig)
	knowledgebaseDomainService := knowledge.ProvideKnowledgeBaseDomainService(baseRepository, vectorDBManagementRepository, dimensionResolver, baseDomainConfig, sugaredLogger)
	knowledgeBaseDocumentRepository := infra.ProvideDocumentRepository(sqlcClient, sugaredLogger)
	documentDomainService := knowledge.ProvideDocumentDomainService(knowledgeBaseDocumentRepository, sugaredLogger)
	phpFileRPCClient := infra.ProvidePHPFileRPCClient(server, sugaredLogger)
	phpocrConfigRPCClient := infra.ProvideOCRConfigProvider(server, sugaredLogger)
	ocrResultCacheRepository := infra.ProvideOCRResultCacheRepository(sqlcClient, sugaredLogger)
	volcengineOCRClient := infra.ProvideVolcengineOCRClient(config, client, phpocrConfigRPCClient, phpocrConfigRPCClient, ocrResultCacheRepository, sugaredLogger)
	v := infra.ProvideDocumentParsers(config, phpFileRPCClient, volcengineOCRClient)
	parseService := infra.ProvideDocumentParseService(config, phpFileRPCClient, v, sugaredLogger)
	phpKnowledgeBasePermissionRPCClient := infra.ProvideKnowledgeBasePermissionPort(server, sugaredLogger)
	phpSuperMagicAgentRPCClient := infra.ProvideSuperMagicAgentPort(server, sugaredLogger)
	phpProjectFileRPCClient := infra.ProvideProjectFilePort(server, sugaredLogger)
	phpThirdPlatformDocumentRPCClient := infra.ProvideThirdPlatformDocumentPort(server, client, sugaredLogger)
	basePortDeps := knowledge.ProvideKnowledgeBasePortDeps(phpKnowledgeBasePermissionRPCClient, phpSuperMagicAgentRPCClient, phpProjectFileRPCClient, phpThirdPlatformDocumentRPCClient)
	registry := knowledge.ProvideThirdPlatformProviderRegistry(phpThirdPlatformDocumentRPCClient, sugaredLogger)
	knowledgebasebindingrepoRepository := infra.ProvideKnowledgeBaseBindingRepository(sqlcClient)
	supermagicagentrepoRepository := infra.ProvideSuperMagicAgentRepository(sqlcClient)
	baseBindingDeps := knowledge.ProvideKnowledgeBaseBindingDeps(knowledgebasebindingrepoRepository, supermagicagentrepoRepository)
	manualFragmentCoordinator := infra.ProvideManualFragmentCoordinator(sqlcClient, sugaredLogger)
	tokenizerService := infra.ProvideTokenizer()
	fragmentAppRuntimeDeps := knowledge.ProvideFragmentAppRuntimeDeps(manualFragmentCoordinator, tokenizerService, embeddingDefaultModel)
	userRepository := infra.ProvideContactUserRepository(sqlcClient)
	userDomainService := infra.ProvideContactUserDomainService(userRepository)
	appDeps := knowledge.ProvideFragmentAppDeps(parseService, basePortDeps, registry, baseBindingDeps, fragmentAppRuntimeDeps, userDomainService)
	fragmentAppService := knowledge.ProvideFragmentAppService(fragmentDomainService, knowledgebaseDomainService, documentDomainService, appDeps, client, sugaredLogger)
	rabbitMQBroker, cleanup4, err := infra.ProvideDocumentSyncRabbitMQBroker(config, sugaredLogger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	runtime := knowledge.ProvideDocumentSyncRuntime(rabbitMQBroker, config, sugaredLogger, server, client)
	serverBackgroundDeps := httpapi.ProvideServerBackgroundDeps(embeddingCacheCleanupService, fragmentAppService, runtime)
	checkService := infra.ProvideHealthCheckService(sqlcClient, client, repository, qdrantClient, rabbitMQBroker)
	metrics := infra.ProvideMetrics()
	docappAppDeps := knowledge.ProvideDocumentAppDeps(parseService, basePortDeps, registry, tokenizerService, userDomainService, sqlcClient)
	redisProgressStore := knowledge.ProvideKnowledgeRevectorizeProgressStore(client)
	documentAppRuntimeDeps := knowledge.ProvideDocumentAppRuntimeDeps(config, phpFileRPCClient, runtime, redisProgressStore, client)
	documentAppService := knowledge.ProvideDocumentAppService(documentDomainService, knowledgebaseDomainService, fragmentDomainService, docappAppDeps, sugaredLogger, documentAppRuntimeDeps)
	baseDocumentFlowDeps := knowledge.ProvideKnowledgeBaseDocumentFlowDeps(documentAppService, documentDomainService, fragmentDomainService, parseService)
	sourcebindingrepoRepository := infra.ProvideSourceBindingRepository(sqlcClient, client, config)
	supermagicprojectrepoRepository := infra.ProvideSuperMagicProjectRepository(sqlcClient)
	supermagicprojectDomainService := knowledge.ProvideSuperMagicProjectDomainService(supermagicprojectrepoRepository)
	taskfileDomainService := infra.ProvideTaskFileDomainService(sqlcClient)
	baseDomainDeps := knowledge.ProvideKnowledgeBaseDomainDeps(supermagicprojectDomainService, taskfileDomainService, userDomainService)
	knowledgeBaseDestroyCoordinator := infra.ProvideKnowledgeBaseDestroyCoordinator(sqlcClient)
	knowledgeBaseWriteCoordinator := infra.ProvideKnowledgeBaseWriteCoordinator(sqlcClient, baseRepository, sourcebindingrepoRepository, knowledgebasebindingrepoRepository)
	baseCoordinatorDeps := knowledge.ProvideKnowledgeBaseCoordinatorDeps(knowledgeBaseDestroyCoordinator, knowledgeBaseWriteCoordinator)
	baseDeps := knowledge.ProvideKnowledgeBaseAppDeps(sourcebindingrepoRepository, baseDomainDeps, basePortDeps, baseCoordinatorDeps, baseBindingDeps)
	knowledgeBaseAppService := knowledge.ProvideKnowledgeBaseAppService(knowledgebaseDomainService, baseDocumentFlowDeps, baseDeps, client, sugaredLogger, embeddingDefaultModel)
	knowledgeRevectorizeAppService := knowledge.ProvideKnowledgeRevectorizeAppService(knowledgeBaseAppService, documentAppService, redisProgressStore, sugaredLogger)
	mySQLStore := infra.ProvideKnowledgeRebuildStore(sqlcClient, client, sugaredLogger)
	coordinator := infra.ProvideVectorRebuildCoordinator(client, sugaredLogger)
	appDocumentResyncer := rebuild.ProvideKnowledgeRebuildResyncer(documentAppService)
	runnerDeps := rebuild.ProvideKnowledgeRebuildRunnerDeps(mySQLStore, coordinator, vectorDBManagementRepository, appDocumentResyncer, dimensionResolver)
	runner, err := rebuild.ProvideKnowledgeRebuildRunner(runnerDeps, config, sugaredLogger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	triggerService := rebuild.ProvideKnowledgeRebuildTriggerService(runner, coordinator, sugaredLogger)
	cleanupService := rebuild.ProvideKnowledgeRebuildCleanupService(mySQLStore, coordinator, vectorDBManagementRepository, phpKnowledgeBasePermissionRPCClient, sugaredLogger)
	knowledgeBaseRPCDeps := service.ProvideKnowledgeBaseRPCDeps(knowledgeRevectorizeAppService, triggerService, cleanupService, client)
	knowledgeBaseRPCService := service.ProvideKnowledgeBaseRPCService(knowledgeBaseAppService, documentAppService, knowledgeBaseRPCDeps, sugaredLogger)
	fragmentRPCService := service.NewFragmentRPCService(fragmentAppService, sugaredLogger)
	documentRPCService := service.NewDocumentRPCService(documentAppService, sugaredLogger)
	embeddingAppService := knowledge.ProvideEmbeddingAppService(domainService, sugaredLogger, embeddingDefaultModel)
	embeddingRPCService := service.NewEmbeddingRPCService(embeddingAppService, sugaredLogger)
	rpcHandlers := httpapi.ProvideRPCHandlers(knowledgeBaseRPCService, fragmentRPCService, documentRPCService, embeddingRPCService)
	debugHandler := handlers.NewDebugHandler(embeddingAppService)
	serverRuntimeDeps := httpapi.ProvideServerRuntimeDeps(server, rpcHandlers, debugHandler)
	serverDependencies := httpapi.ProvideServerDependencies(serverConfig, serverBackgroundDeps, checkService, sugaredLogger, metrics, serverRuntimeDeps)
	httpapiServer := httpapi.NewServerWithDependencies(serverDependencies)
	return httpapiServer, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func provideServerConfig(cfg *autoload.Config) *httpapi.ServerConfig {
	httpEnabled := false
	if cfg.Server.Enabled != nil {
		httpEnabled = *cfg.Server.Enabled
	}

	return &httpapi.ServerConfig{
		Enabled:        httpEnabled,
		Host:           cfg.Server.Host,
		Port:           cfg.Server.Port,
		Mode:           httpapi.Mode(cfg.Server.Mode),
		BasePath:       cfg.Server.BasePath,
		Env:            cfg.Server.Env,
		PprofEnabled:   cfg.Server.PprofEnabled,
		AllowedOrigins: cfg.Security.AllowedOrigins,
	}
}
